# Mutual Fund Outperformance Prediction

## ML Model Development

### Objective

Predict whether an active equity mutual fund will outperform the
Nifty 500 TRI in the following month.

### Prediction structure

Features at month t
        ↓
Predict
        ↓
Outperformance at month t+1

### Data period

January 2019 – December 2025

### Feature-selection methodology

1. Candidate characteristics
2. Information Coefficient screening
3. Retain characteristics with |IC| >= 0.03
4. ML-based feature selection
5. Rolling out-of-sample prediction

### ML models

- Random Forest
- XGBoost
- LightGBM

### Validation methodology

Rolling training windows with 5-fold time-series
cross-validation and 3-month out-of-sample prediction periods.

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from pathlib import Path

from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

import warnings

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 180)

In [2]:
# ============================================================
# CONFIGURATION
# ============================================================

DATA_FILE = Path(
    "feature_selection_output/ml_feature_dataset.csv"
)

IC_FILE = Path(
    "feature_selection_output/ic_selected_features.csv"
)

OUTPUT_DIR = Path(
    "feature_selection_output"
)

OUTPUT_DIR.mkdir(
    exist_ok=True
)

# ------------------------------------------------------------
# Research period
# ------------------------------------------------------------

MODEL_START_MONTH = pd.Timestamp("2019-01-01")
MODEL_END_MONTH = pd.Timestamp("2025-12-01")

# ------------------------------------------------------------
# Rolling framework
# ------------------------------------------------------------

INITIAL_TRAIN_MONTHS = 60

OOS_MONTHS = 3

ROLL_MONTHS = 3

# ------------------------------------------------------------
# Cross-validation
# ------------------------------------------------------------

N_CV_SPLITS = 5

print("Model period:")
print(
    MODEL_START_MONTH.date(),
    "→",
    MODEL_END_MONTH.date()
)

print()
print("Initial training months:", INITIAL_TRAIN_MONTHS)
print("OOS months:", OOS_MONTHS)
print("Roll months:", ROLL_MONTHS)
print("CV folds:", N_CV_SPLITS)

Model period:
2019-01-01 → 2025-12-01

Initial training months: 60
OOS months: 3
Roll months: 3
CV folds: 5

In [3]:
# ============================================================
# LOAD ML DATASET
# ============================================================

df = pd.read_csv(
    DATA_FILE
)

df["month_date"] = pd.to_datetime(
    df["month_date"]
)

df["target_month"] = pd.to_datetime(
    df["target_month"]
)

df = df.sort_values(
    ["month_date", "scheme_name"]
).reset_index(
    drop=True
)

print("Raw ML dataset shape:", df.shape)

print(
    "Raw date range:",
    df["month_date"].min().date(),
    "→",
    df["month_date"].max().date()
)

Raw ML dataset shape: (7034, 29)
Raw date range: 2019-01-01 → 2026-06-01

In [4]:
# ============================================================
# LOAD IC-SELECTED FEATURES
# ============================================================

ic_selected = pd.read_csv(
    IC_FILE
)

selected_features = (
    ic_selected[
        ic_selected["ic_pass"] == "PASS"
    ]["predictor"]
    .dropna()
    .tolist()
)

print(
    "Number of IC-selected features:",
    len(selected_features)
)

for i, feature in enumerate(
    selected_features,
    start=1
):
    print(
        f"{i:2d}. {feature}"
    )

Number of IC-selected features: 25
 1. t_hml_250
 2. t_hml_750
 3. t_hml_180
 4. sr_p1y
 5. ir_p1y
 6. ir_p6m
 7. monthly_return_percent
 8. t_const_180
 9. sr_p6m
10. t_const_250
11. ir_p3y
12. const_90
13. const_180
14. t_const_90
15. t_const_120
16. const_250
17. t_hml_120
18. const_120
19. t_mkt_750
20. t_umd_750
21. t_hml_90
22. sr_p3y
23. r2_750
24. net_flow_percent
25. t_smb_250

In [5]:
# ============================================================
# RESTRICT TO USABLE RESEARCH PERIOD
# ============================================================

model_df = df[
    (df["month_date"] >= MODEL_START_MONTH) &
    (df["month_date"] <= MODEL_END_MONTH)
].copy()

model_df = model_df.sort_values(
    ["month_date", "scheme_name"]
).reset_index(
    drop=True
)

print(
    "Model dataset shape:",
    model_df.shape
)

print(
    "Model date range:",
    model_df["month_date"].min().date(),
    "→",
    model_df["month_date"].max().date()
)

print(
    "Unique months:",
    model_df["month_date"].nunique()
)

Model dataset shape: (6150, 29)
Model date range: 2019-01-01 → 2025-12-01
Unique months: 84

In [6]:
# ============================================================
# TARGET VALIDATION
# ============================================================

TARGET = "outperforms_benchmark"

print(
    model_df[TARGET].value_counts()
)

print()

print(
    model_df[TARGET]
    .value_counts(normalize=True)
)

outperforms_benchmark
1    3155
0    2995
Name: count, dtype: int64

outperforms_benchmark
1    0.513008
0    0.486992
Name: proportion, dtype: float64

In [7]:
# ============================================================
# VERIFY ONE-MONTH-AHEAD TARGET
# ============================================================

target_check = (
    model_df[
        ["month_date", "target_month"]
    ]
    .drop_duplicates()
    .copy()
)

target_check["month_diff"] = (
    target_check["target_month"]
    .dt.to_period("M")
    .astype(int)
    -
    target_check["month_date"]
    .dt.to_period("M")
    .astype(int)
)

print(
    target_check["month_diff"]
    .value_counts()
)

month_diff
1    84
Name: count, dtype: int64

In [8]:
# ============================================================
# FEATURE AVAILABILITY
# ============================================================

feature_missing = (
    model_df[selected_features]
    .isna()
    .sum()
    .sort_values(
        ascending=False
    )
)

feature_missing_pct = (
    feature_missing /
    len(model_df) *
    100
)

feature_availability = pd.DataFrame({
    "missing_rows": feature_missing,
    "missing_percent": feature_missing_pct
})

display(
    feature_availability
)

                        missing_rows  missing_percent
t_hml_750                       4158        67.609756
t_mkt_750                       4158        67.609756
t_umd_750                       4158        67.609756
r2_750                          4158        67.609756
sr_p3y                          4158        67.609756
ir_p3y                          4158        67.609756
t_hml_250                       1734        28.195122
ir_p1y                          1734        28.195122
sr_p1y                          1734        28.195122
const_250                       1734        28.195122
t_const_250                     1734        28.195122
t_smb_250                       1734        28.195122
const_180                       1270        20.650407
t_hml_180                       1270        20.650407
t_const_180                     1270        20.650407
ir_p6m                           907        14.747967
sr_p6m                           907        14.747967
t_const_120                      836        13.593496
const_120                        836        13.593496
t_hml_120                        836        13.593496
t_const_90                       659        10.715447
t_hml_90                         659        10.715447
const_90                         659        10.715447
monthly_return_percent           180         2.926829
net_flow_percent                 180         2.926829

In [9]:
# ============================================================
# ROLLING OUT-OF-SAMPLE WINDOWS
# ============================================================

unique_months = (
    model_df["month_date"]
    .drop_duplicates()
    .sort_values()
    .tolist()
)

rolling_windows = []

start_idx = 0

while True:

    train_start_idx = start_idx

    train_end_idx = (
        train_start_idx
        + INITIAL_TRAIN_MONTHS
        - 1
    )

    oos_start_idx = train_end_idx + 1

    oos_end_idx = (
        oos_start_idx
        + OOS_MONTHS
        - 1
    )

    # Require a complete 3-month OOS period
    if oos_end_idx >= len(unique_months):
        break

    rolling_windows.append({
        "window": len(rolling_windows) + 1,
        "train_start": unique_months[train_start_idx],
        "train_end": unique_months[train_end_idx],
        "oos_start": unique_months[oos_start_idx],
        "oos_end": unique_months[oos_end_idx]
    })

    start_idx += ROLL_MONTHS


rolling_windows_df = pd.DataFrame(
    rolling_windows
)

display(rolling_windows_df)

print(
    f"Usable rolling windows: "
    f"{len(rolling_windows_df)}"
)

print(
    f"OOS months: "
    f"{len(rolling_windows_df) * OOS_MONTHS}"
)

   window train_start  train_end  oos_start    oos_end
0       1  2019-01-01 2023-12-01 2024-01-01 2024-03-01
1       2  2019-04-01 2024-03-01 2024-04-01 2024-06-01
2       3  2019-07-01 2024-06-01 2024-07-01 2024-09-01
3       4  2019-10-01 2024-09-01 2024-10-01 2024-12-01
4       5  2020-01-01 2024-12-01 2025-01-01 2025-03-01
5       6  2020-04-01 2025-03-01 2025-04-01 2025-06-01
6       7  2020-07-01 2025-06-01 2025-07-01 2025-09-01
7       8  2020-10-01 2025-09-01 2025-10-01 2025-12-01

Usable rolling windows: 8
OOS months: 24

In [10]:
# ============================================================
# VALIDATE ROLLING WINDOWS
# ============================================================

for _, row in rolling_windows_df.iterrows():

    assert row["train_start"] < row["train_end"]
    assert row["train_end"] < row["oos_start"]
    assert row["oos_start"] <= row["oos_end"]

    print(
        f"Window {int(row['window']):2d}: "
        f"TRAIN {row['train_start'].strftime('%Y-%m')} "
        f"→ {row['train_end'].strftime('%Y-%m')} | "
        f"OOS {row['oos_start'].strftime('%Y-%m')} "
        f"→ {row['oos_end'].strftime('%Y-%m')}"
    )

Window  1: TRAIN 2019-01 → 2023-12 | OOS 2024-01 → 2024-03
Window  2: TRAIN 2019-04 → 2024-03 | OOS 2024-04 → 2024-06
Window  3: TRAIN 2019-07 → 2024-06 | OOS 2024-07 → 2024-09
Window  4: TRAIN 2019-10 → 2024-09 | OOS 2024-10 → 2024-12
Window  5: TRAIN 2020-01 → 2024-12 | OOS 2025-01 → 2025-03
Window  6: TRAIN 2020-04 → 2025-03 | OOS 2025-04 → 2025-06
Window  7: TRAIN 2020-07 → 2025-06 | OOS 2025-07 → 2025-09
Window  8: TRAIN 2020-10 → 2025-09 | OOS 2025-10 → 2025-12

In [11]:
# ============================================================
# PREPARE ROLLING DATASETS
# ============================================================

rolling_data = []

for _, window in rolling_windows_df.iterrows():

    train = model_df[
        (model_df["month_date"] >= window["train_start"]) &
        (model_df["month_date"] <= window["train_end"])
    ].copy()

    oos = model_df[
        (model_df["month_date"] >= window["oos_start"]) &
        (model_df["month_date"] <= window["oos_end"])
    ].copy()

    rolling_data.append({
        "window": int(window["window"]),
        "train": train,
        "oos": oos
    })

    print(
        f"Window {int(window['window']):2d}: "
        f"TRAIN rows={len(train):4d}, "
        f"OOS rows={len(oos):4d}"
    )

Window  1: TRAIN rows=3268, OOS rows= 295
Window  2: TRAIN rows=3481, OOS rows= 306
Window  3: TRAIN rows=3706, OOS rows= 322
Window  4: TRAIN rows=3945, OOS rows= 337
Window  5: TRAIN rows=4186, OOS rows= 357
Window  6: TRAIN rows=4439, OOS rows= 411
Window  7: TRAIN rows=4743, OOS rows= 419
Window  8: TRAIN rows=5051, OOS rows= 435

In [12]:
# ============================================================
# MISSINGNESS ANALYSIS — BY FEATURE
# ============================================================

missing_by_feature = (
    model_df[selected_features]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

missing_summary = pd.DataFrame({
    "missing_rows": missing_by_feature,
    "total_rows": len(model_df),
    "missing_pct": (
        missing_by_feature / len(model_df) * 100
    )
})

display(
    missing_summary.round(2)
)

                        missing_rows  total_rows  missing_pct
t_hml_750                       4158        6150        67.61
t_mkt_750                       4158        6150        67.61
t_umd_750                       4158        6150        67.61
r2_750                          4158        6150        67.61
sr_p3y                          4158        6150        67.61
ir_p3y                          4158        6150        67.61
t_hml_250                       1734        6150        28.20
ir_p1y                          1734        6150        28.20
sr_p1y                          1734        6150        28.20
const_250                       1734        6150        28.20
t_const_250                     1734        6150        28.20
t_smb_250                       1734        6150        28.20
const_180                       1270        6150        20.65
t_hml_180                       1270        6150        20.65
t_const_180                     1270        6150        20.65
ir_p6m                           907        6150        14.75
sr_p6m                           907        6150        14.75
t_const_120                      836        6150        13.59
const_120                        836        6150        13.59
t_hml_120                        836        6150        13.59
t_const_90                       659        6150        10.72
t_hml_90                         659        6150        10.72
const_90                         659        6150        10.72
monthly_return_percent           180        6150         2.93
net_flow_percent                 180        6150         2.93

In [13]:
# ============================================================
# MISSINGNESS ANALYSIS — BY MONTH
# ============================================================

monthly_missing = (
    model_df
    .groupby("month_date")[selected_features]
    .apply(lambda x: x.isna().sum().sum())
)

monthly_total = (
    model_df
    .groupby("month_date")
    .size()
    * len(selected_features)
)

monthly_missing_pct = (
    monthly_missing / monthly_total * 100
)

monthly_missing_summary = pd.DataFrame({
    "missing_cells": monthly_missing,
    "total_feature_cells": monthly_total,
    "missing_pct": monthly_missing_pct
})

display(
    monthly_missing_summary.round(2)
)

            missing_cells  total_feature_cells  missing_pct
month_date
2019-01-01            700                  700       100.00
2019-02-01            675                  675       100.00
2019-03-01            621                  675        92.00
2019-04-01            621                  675        92.00
2019-05-01            543                  675        80.44
...                   ...                  ...          ...
2025-08-01            788                 3475        22.68
2025-09-01            716                 3575        20.03
2025-10-01            752                 3625        20.74
2025-11-01            736                 3625        20.30
2025-12-01            634                 3625        17.49

[84 rows x 3 columns]

In [14]:
display(
    monthly_missing_summary.tail(24).round(2)
)

            missing_cells  total_feature_cells  missing_pct
month_date
2024-01-01            521                 2400        21.71
2024-02-01            575                 2475        23.23
2024-03-01            586                 2500        23.44
2024-04-01            567                 2500        22.68
2024-05-01            580                 2525        22.97
2024-06-01            662                 2625        25.22
2024-07-01            655                 2650        24.72
2024-08-01            618                 2650        23.32
2024-09-01            691                 2750        25.13
2024-10-01            685                 2775        24.68
2024-11-01            718                 2825        25.42
2024-12-01            526                 2825        18.62
2025-01-01            434                 2825        15.36
2025-02-01            398                 2825        14.09
2025-03-01            798                 3275        24.37
2025-04-01            901                 3425        26.31
2025-05-01            870                 3425        25.40
2025-06-01            831                 3425        24.26
2025-07-01            810                 3425        23.65
2025-08-01            788                 3475        22.68
2025-09-01            716                 3575        20.03
2025-10-01            752                 3625        20.74
2025-11-01            736                 3625        20.30
2025-12-01            634                 3625        17.49

In [15]:
# ============================================================
# COMPLETE FEATURE VECTORS
# ============================================================

complete_feature_mask = (
    model_df[selected_features]
    .notna()
    .all(axis=1)
)

print(
    "Total fund-month observations:",
    len(model_df)
)

print(
    "Complete feature vectors:",
    complete_feature_mask.sum()
)

print(
    "Incomplete feature vectors:",
    (~complete_feature_mask).sum()
)

print(
    "Complete:",
    round(
        complete_feature_mask.mean() * 100,
        2
    ),
    "%"
)

Total fund-month observations: 6150
Complete feature vectors: 1992
Incomplete feature vectors: 4158
Complete: 32.39 %

In [16]:
# ============================================================
# COMPLETE OBSERVATIONS BY MONTH
# ============================================================

monthly_complete = (
    model_df
    .assign(
        complete_features=complete_feature_mask
    )
    .groupby("month_date")
    .agg(
        total_funds=("scheme_name", "size"),
        complete_funds=("complete_features", "sum")
    )
)

monthly_complete["complete_pct"] = (
    monthly_complete["complete_funds"]
    / monthly_complete["total_funds"]
    * 100
)

display(
    monthly_complete
)

            total_funds  complete_funds  complete_pct
month_date
2019-01-01           28               0      0.000000
2019-02-01           27               0      0.000000
2019-03-01           27               0      0.000000
2019-04-01           27               0      0.000000
2019-05-01           27               0      0.000000
...                 ...             ...           ...
2025-08-01          139              77     55.395683
2025-09-01          143              81     56.643357
2025-10-01          145              81     55.862069
2025-11-01          145              81     55.862069
2025-12-01          145              85     58.620690

[84 rows x 3 columns]

In [17]:
# ============================================================
# CONTRIBUTION TO INCOMPLETE OBSERVATIONS
# ============================================================

incomplete_cause = []

for feature in selected_features:

    missing = model_df[feature].isna()

    incomplete_cause.append({
        "feature": feature,
        "missing_rows": missing.sum(),
        "missing_pct": missing.mean() * 100
    })

incomplete_cause = pd.DataFrame(
    incomplete_cause
).sort_values(
    "missing_rows",
    ascending=False
)

display(
    incomplete_cause.round(2)
)

                   feature  missing_rows  missing_pct
1                t_hml_750          4158        67.61
18               t_mkt_750          4158        67.61
19               t_umd_750          4158        67.61
22                  r2_750          4158        67.61
21                  sr_p3y          4158        67.61
10                  ir_p3y          4158        67.61
0                t_hml_250          1734        28.20
4                   ir_p1y          1734        28.20
3                   sr_p1y          1734        28.20
15               const_250          1734        28.20
9              t_const_250          1734        28.20
24               t_smb_250          1734        28.20
12               const_180          1270        20.65
2                t_hml_180          1270        20.65
7              t_const_180          1270        20.65
5                   ir_p6m           907        14.75
8                   sr_p6m           907        14.75
14             t_const_120           836        13.59
17               const_120           836        13.59
16               t_hml_120           836        13.59
13              t_const_90           659        10.72
20                t_hml_90           659        10.72
11                const_90           659        10.72
6   monthly_return_percent           180         2.93
23        net_flow_percent           180         2.93

In [18]:
# ============================================================
# FIRST AVAILABLE MONTH BY FEATURE
# ============================================================

first_available = []

for feature in selected_features:

    available = model_df.loc[
        model_df[feature].notna(),
        "month_date"
    ]

    first_available.append({
        "feature": feature,
        "first_available_month": (
            available.min()
            if not available.empty
            else pd.NaT
        ),
        "last_available_month": (
            available.max()
            if not available.empty
            else pd.NaT
        )
    })

feature_history = pd.DataFrame(
    first_available
)

display(
    feature_history.sort_values(
        "first_available_month"
    )
)

                   feature first_available_month last_available_month
6   monthly_return_percent            2019-03-01           2025-12-01
23        net_flow_percent            2019-03-01           2025-12-01
20                t_hml_90            2019-05-01           2025-12-01
11                const_90            2019-05-01           2025-12-01
13              t_const_90            2019-05-01           2025-12-01
17               const_120            2019-06-01           2025-12-01
16               t_hml_120            2019-06-01           2025-12-01
14             t_const_120            2019-06-01           2025-12-01
5                   ir_p6m            2019-07-01           2025-12-01
8                   sr_p6m            2019-07-01           2025-12-01
12               const_180            2019-09-01           2025-12-01
2                t_hml_180            2019-09-01           2025-12-01
7              t_const_180            2019-09-01           2025-12-01
15               const_250            2020-01-01           2025-12-01
0                t_hml_250            2020-01-01           2025-12-01
9              t_const_250            2020-01-01           2025-12-01
4                   ir_p1y            2020-01-01           2025-12-01
3                   sr_p1y            2020-01-01           2025-12-01
24               t_smb_250            2020-01-01           2025-12-01
18               t_mkt_750            2022-01-01           2025-12-01
19               t_umd_750            2022-01-01           2025-12-01
1                t_hml_750            2022-01-01           2025-12-01
21                  sr_p3y            2022-01-01           2025-12-01
22                  r2_750            2022-01-01           2025-12-01
10                  ir_p3y            2022-01-01           2025-12-01

In [20]:
# ============================================================
# ROLLING WINDOW — FEATURE AVAILABILITY CHECK
# ============================================================

for _, w in rolling_windows_df.iterrows():

    train = model_df[
        (model_df["month_date"] >= w["train_start"]) &
        (model_df["month_date"] <= w["train_end"])
    ].copy()

    oos = model_df[
        (model_df["month_date"] >= w["oos_start"]) &
        (model_df["month_date"] <= w["oos_end"])
    ].copy()

    train_complete = train.dropna(
        subset=selected_features + [TARGET]
    )

    oos_complete = oos.dropna(
        subset=selected_features + [TARGET]
    )

    print(
        f"Window {int(w['window']):2d}: "
        f"TRAIN {len(train_complete):4d}/{len(train):4d} "
        f"({len(train_complete)/len(train)*100:5.1f}%) | "
        f"OOS {len(oos_complete):3d}/{len(oos):3d} "
        f"({len(oos_complete)/len(oos)*100:5.1f}%)"
    )

Window  1: TRAIN  646/3268 ( 19.8%) | OOS  96/295 ( 32.5%)
Window  2: TRAIN  742/3481 ( 21.3%) | OOS  97/306 ( 31.7%)
Window  3: TRAIN  839/3706 ( 22.6%) | OOS  99/322 ( 30.7%)
Window  4: TRAIN  938/3945 ( 23.8%) | OOS 126/337 ( 37.4%)
Window  5: TRAIN 1064/4186 ( 25.4%) | OOS 220/357 ( 61.6%)
Window  6: TRAIN 1284/4439 ( 28.9%) | OOS 226/411 ( 55.0%)
Window  7: TRAIN 1510/4743 ( 31.8%) | OOS 235/419 ( 56.1%)
Window  8: TRAIN 1745/5051 ( 34.5%) | OOS 247/435 ( 56.8%)

In [22]:
# ============================================================
# 11. ROLLING 5-FOLD CROSS-VALIDATION
# ============================================================

from sklearn.model_selection import KFold

N_FOLDS = 5
RANDOM_STATE = 42

cv = KFold(
    n_splits=N_FOLDS,
    shuffle=False

)

print(f"K-fold CV: {N_FOLDS} folds")
print(f"Shuffle: false")
print(f"Random state: {RANDOM_STATE}")

K-fold CV: 5 folds
Shuffle: false
Random state: 42

In [23]:
# ============================================================
# PREPARE TRAINING DATA FOR EACH ROLLING WINDOW
# ============================================================

rolling_train_data = []

for _, w in rolling_windows_df.iterrows():

    window_id = int(w["window"])

    train = model_df[
        (model_df["month_date"] >= w["train_start"]) &
        (model_df["month_date"] <= w["train_end"])
    ].copy()

    # Remove observations with missing selected features/target
    train_complete = train.dropna(
        subset=selected_features + [TARGET]
    ).copy()

    X = train_complete[selected_features]
    y = train_complete[TARGET].astype(int)

    rolling_train_data.append({
        "window": window_id,
        "train_start": w["train_start"],
        "train_end": w["train_end"],
        "data": train_complete,
        "X": X,
        "y": y
    })

    print(
        f"Window {window_id}: "
        f"{len(train_complete)} usable observations | "
        f"class 0 = {(y == 0).sum()} | "
        f"class 1 = {(y == 1).sum()}"
    )

Window 1: 646 usable observations | class 0 = 272 | class 1 = 374
Window 2: 742 usable observations | class 0 = 315 | class 1 = 427
Window 3: 839 usable observations | class 0 = 368 | class 1 = 471
Window 4: 938 usable observations | class 0 = 388 | class 1 = 550
Window 5: 1064 usable observations | class 0 = 450 | class 1 = 614
Window 6: 1284 usable observations | class 0 = 549 | class 1 = 735
Window 7: 1510 usable observations | class 0 = 653 | class 1 = 857
Window 8: 1745 usable observations | class 0 = 812 | class 1 = 933

In [24]:
# ============================================================
# TARGET BALANCE CHECK
# ============================================================

for item in rolling_train_data:

    y = item["y"]

    counts = y.value_counts().sort_index()

    print(
        f"\nWindow {item['window']}"
    )

    print(
        f"  Class 0: {counts.get(0, 0)} "
        f"({counts.get(0, 0) / len(y) * 100:.1f}%)"
    )

    print(
        f"  Class 1: {counts.get(1, 0)} "
        f"({counts.get(1, 0) / len(y) * 100:.1f}%)"
    )

Window 1
  Class 0: 272 (42.1%)
  Class 1: 374 (57.9%)

Window 2
  Class 0: 315 (42.5%)
  Class 1: 427 (57.5%)

Window 3
  Class 0: 368 (43.9%)
  Class 1: 471 (56.1%)

Window 4
  Class 0: 388 (41.4%)
  Class 1: 550 (58.6%)

Window 5
  Class 0: 450 (42.3%)
  Class 1: 614 (57.7%)

Window 6
  Class 0: 549 (42.8%)
  Class 1: 735 (57.2%)

Window 7
  Class 0: 653 (43.2%)
  Class 1: 857 (56.8%)

Window 8
  Class 0: 812 (46.5%)
  Class 1: 933 (53.5%)

In [25]:
# ============================================================
# RANDOM FOREST — TEST CV
# ============================================================

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

rf_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    (
        "model",
        RandomForestClassifier(
            random_state=RANDOM_STATE,
            n_jobs=-1,
            class_weight="balanced"
        )
    )
])

rf_param_grid = {
    "model__n_estimators": [200, 500],
    "model__max_depth": [3, 5, None],
    "model__min_samples_leaf": [5, 10]
}

In [25]:
# # ============================================================
# # TEST RF CV ON WINDOW 1
# # ============================================================
#
# window_1 = rolling_train_data[0]
#
# X_train = window_1["X"]
# y_train = window_1["y"]
#
# rf_grid = GridSearchCV(
#     estimator=rf_pipeline,
#     param_grid=rf_param_grid,
#     cv=cv,
#     scoring="roc_auc",
#     n_jobs=-1,
#     refit=True,
#     return_train_score=False
# )
#
# rf_grid.fit(X_train, y_train)
#
# print("Window 1 RF CV complete")
# print()
# print("Best parameters:")
# print(rf_grid.best_params_)
# print()
# print(
#     f"Best CV ROC-AUC: "
#     f"{rf_grid.best_score_:.4f}"
# )

In [26]:
# ============================================================
# RANDOM FOREST — 5-FOLD CV FOR ALL ROLLING WINDOWS
# ============================================================

rf_cv_results = []

for item in rolling_train_data:

    window_id = item["window"]

    X_train = item["X"]
    y_train = item["y"]

    print(
        f"\nWindow {window_id}: "
        f"{len(X_train)} observations"
    )

    rf_grid = GridSearchCV(
        estimator=rf_pipeline,
        param_grid=rf_param_grid,
        cv=cv,
        scoring="roc_auc",
        n_jobs=-1,
        refit=True,
        return_train_score=False
    )

    rf_grid.fit(X_train, y_train)

    result = {
        "window": window_id,
        "train_start": item["train_start"],
        "train_end": item["train_end"],
        "n_train": len(X_train),
        "best_cv_auc": rf_grid.best_score_,
        "best_n_estimators":
            rf_grid.best_params_["model__n_estimators"],
        "best_max_depth":
            rf_grid.best_params_["model__max_depth"],
        "best_min_samples_leaf":
            rf_grid.best_params_["model__min_samples_leaf"],
    }

    rf_cv_results.append(result)

    print(
        f"  Best AUC: {rf_grid.best_score_:.4f}"
    )

    print(
        f"  Best params: {rf_grid.best_params_}"
    )


rf_cv_results_df = pd.DataFrame(rf_cv_results)

display(
    rf_cv_results_df.round(4)
)

Window 1: 646 observations
  Best AUC: 0.5851
  Best params: {'model__max_depth': 5, 'model__min_samples_leaf': 10, 'model__n_estimators': 200}

Window 2: 742 observations
  Best AUC: 0.5843
  Best params: {'model__max_depth': 3, 'model__min_samples_leaf': 5, 'model__n_estimators': 500}

Window 3: 839 observations
  Best AUC: 0.5781
  Best params: {'model__max_depth': 3, 'model__min_samples_leaf': 5, 'model__n_estimators': 200}

Window 4: 938 observations
  Best AUC: 0.5694
  Best params: {'model__max_depth': 3, 'model__min_samples_leaf': 5, 'model__n_estimators': 200}

Window 5: 1064 observations
  Best AUC: 0.5816
  Best params: {'model__max_depth': 5, 'model__min_samples_leaf': 5, 'model__n_estimators': 200}

Window 6: 1284 observations
  Best AUC: 0.5410
  Best params: {'model__max_depth': 3, 'model__min_samples_leaf': 5, 'model__n_estimators': 500}

Window 7: 1510 observations
  Best AUC: 0.5635
  Best params: {'model__max_depth': 3, 'model__min_samples_leaf': 5, 'model__n_estimators': 500}

Window 8: 1745 observations
  Best AUC: 0.4888
  Best params: {'model__max_depth': None, 'model__min_samples_leaf': 10, 'model__n_estimators': 200}

   window train_start  train_end  n_train  best_cv_auc  best_n_estimators  best_max_depth  best_min_samples_leaf
0       1  2019-01-01 2023-12-01      646       0.5851                200             5.0                     10
1       2  2019-04-01 2024-03-01      742       0.5843                500             3.0                      5
2       3  2019-07-01 2024-06-01      839       0.5781                200             3.0                      5
3       4  2019-10-01 2024-09-01      938       0.5694                200             3.0                      5
4       5  2020-01-01 2024-12-01     1064       0.5816                200             5.0                      5
5       6  2020-04-01 2025-03-01     1284       0.5410                500             3.0                      5
6       7  2020-07-01 2025-06-01     1510       0.5635                500             3.0                      5
7       8  2020-10-01 2025-09-01     1745       0.4888                200             NaN                     10

In [30]:
# ============================================================
# RANDOM FOREST — ROLLING OOS PREDICTIONS
# ============================================================

rf_oos_predictions = []

for _, w in rolling_windows_df.iterrows():

    window_id = int(w["window"])

    print(f"\n{'=' * 70}")
    print(f"Window {window_id}")
    print(
        f"TRAIN: {w['train_start'].strftime('%Y-%m')} "
        f"→ {w['train_end'].strftime('%Y-%m')}"
    )
    print(
        f"OOS:   {w['oos_start'].strftime('%Y-%m')} "
        f"→ {w['oos_end'].strftime('%Y-%m')}"
    )

    # --------------------------------------------------------
    # TRAINING DATA
    # --------------------------------------------------------

    train = model_df[
        (model_df["month_date"] >= w["train_start"]) &
        (model_df["month_date"] <= w["train_end"])
    ].copy()

    train = train.dropna(
        subset=selected_features + [TARGET]
    ).copy()

    X_train = train[selected_features]
    y_train = train[TARGET].astype(int)

    # --------------------------------------------------------
    # OOS DATA
    # --------------------------------------------------------

    oos = model_df[
        (model_df["month_date"] >= w["oos_start"]) &
        (model_df["month_date"] <= w["oos_end"])
    ].copy()

    # Keep only observations with all model features available
    # Target is NOT required for making predictions
    oos_predict = oos.dropna(
        subset=selected_features
    ).copy()

    X_oos = oos_predict[selected_features]

    # --------------------------------------------------------
    # GET BEST HYPERPARAMETERS FOR THIS WINDOW
    # --------------------------------------------------------

    cv_result = rf_cv_results_df[
        rf_cv_results_df["window"] == window_id
    ].iloc[0]

    # --------------------------------------------------------
    # Convert parameters to the correct Python types
    # --------------------------------------------------------

    max_depth_value = cv_result["best_max_depth"]

    if pd.isna(max_depth_value):
        max_depth_value = None
    else:
        max_depth_value = int(max_depth_value)

    best_params = {
        "model__n_estimators": int(
            cv_result["best_n_estimators"]
        ),

        "model__max_depth": max_depth_value,

        "model__min_samples_leaf": int(
            cv_result["best_min_samples_leaf"]
        )
    }

    print("Best parameters:")
    print(best_params)

    # --------------------------------------------------------
    # CREATE FINAL RF FOR THIS WINDOW
    # --------------------------------------------------------

    rf_final = Pipeline([
    ("scaler", StandardScaler()),
    (
        "model",
        RandomForestClassifier(
            random_state=RANDOM_STATE,
            n_jobs=-1,
            class_weight="balanced",
            n_estimators=best_params["model__n_estimators"],
            max_depth=best_params["model__max_depth"],
            min_samples_leaf=best_params["model__min_samples_leaf"]
        )
    )
    ])

    # --------------------------------------------------------
    # FIT ON ENTIRE USABLE TRAINING WINDOW
    # --------------------------------------------------------

    rf_final.fit(
        X_train,
        y_train
    )

    # --------------------------------------------------------
    # OOS PREDICTIONS
    # --------------------------------------------------------

    oos_predict["rf_probability"] = (
        rf_final.predict_proba(X_oos)[:, 1]
    )

    oos_predict["rf_prediction"] = (
        rf_final.predict(X_oos)
    )

    oos_predict["rf_window"] = window_id

    oos_predict["rf_train_start"] = w["train_start"]
    oos_predict["rf_train_end"] = w["train_end"]

    oos_predict["rf_oos_start"] = w["oos_start"]
    oos_predict["rf_oos_end"] = w["oos_end"]

    rf_oos_predictions.append(
        oos_predict
    )

    print(
        f"Training observations: {len(train):,}"
    )

    print(
        f"OOS observations:      {len(oos_predict):,}"
    )

    print(
        f"Mean P(outperformance): "
        f"{oos_predict['rf_probability'].mean():.4f}"
    )


rf_oos_df = pd.concat(
    rf_oos_predictions,
    ignore_index=True
)

print("\n")
print("=" * 70)
print("RF OOS prediction complete")
print("=" * 70)

print(
    "Total OOS predictions:",
    len(rf_oos_df)
)

print(
    "Unique funds:",
    rf_oos_df["scheme_name"].nunique()
)

print(
    "OOS months:",
    rf_oos_df["month_date"].nunique()
)

display(
    rf_oos_df[
        [
            "rf_window",
            "scheme_name",
            "month_date",
            TARGET,
            "rf_probability",
            "rf_prediction"
        ]
    ].head(20)
)

======================================================================
Window 1
TRAIN: 2019-01 → 2023-12
OOS:   2024-01 → 2024-03
Best parameters:
{'model__n_estimators': 200, 'model__max_depth': 5, 'model__min_samples_leaf': 10}
Training observations: 646
OOS observations:      96
Mean P(outperformance): 0.4587

======================================================================
Window 2
TRAIN: 2019-04 → 2024-03
OOS:   2024-04 → 2024-06
Best parameters:
{'model__n_estimators': 500, 'model__max_depth': 3, 'model__min_samples_leaf': 5}
Training observations: 742
OOS observations:      97
Mean P(outperformance): 0.4713

======================================================================
Window 3
TRAIN: 2019-07 → 2024-06
OOS:   2024-07 → 2024-09
Best parameters:
{'model__n_estimators': 200, 'model__max_depth': 3, 'model__min_samples_leaf': 5}
Training observations: 839
OOS observations:      99
Mean P(outperformance): 0.4544

======================================================================
Window 4
TRAIN: 2019-10 → 2024-09
OOS:   2024-10 → 2024-12
Best parameters:
{'model__n_estimators': 200, 'model__max_depth': 3, 'model__min_samples_leaf': 5}
Training observations: 938
OOS observations:      126
Mean P(outperformance): 0.5183

======================================================================
Window 5
TRAIN: 2020-01 → 2024-12
OOS:   2025-01 → 2025-03
Best parameters:
{'model__n_estimators': 200, 'model__max_depth': 5, 'model__min_samples_leaf': 5}
Training observations: 1,064
OOS observations:      220
Mean P(outperformance): 0.4145

======================================================================
Window 6
TRAIN: 2020-04 → 2025-03
OOS:   2025-04 → 2025-06
Best parameters:
{'model__n_estimators': 500, 'model__max_depth': 3, 'model__min_samples_leaf': 5}
Training observations: 1,284
OOS observations:      226
Mean P(outperformance): 0.5049

======================================================================
Window 7
TRAIN: 2020-07 → 2025-06
OOS:   2025-07 → 2025-09
Best parameters:
{'model__n_estimators': 500, 'model__max_depth': 3, 'model__min_samples_leaf': 5}
Training observations: 1,510
OOS observations:      235
Mean P(outperformance): 0.5404

======================================================================
Window 8
TRAIN: 2020-10 → 2025-09
OOS:   2025-10 → 2025-12
Best parameters:
{'model__n_estimators': 200, 'model__max_depth': None, 'model__min_samples_leaf': 10}
Training observations: 1,745
OOS observations:      247
Mean P(outperformance): 0.4463


======================================================================
RF OOS prediction complete
======================================================================
Total OOS predictions: 1346
Unique funds: 85
OOS months: 24

    rf_window                                scheme_name month_date  outperforms_benchmark  rf_probability  rf_prediction
0           1                        Axis Flexi Cap Fund 2024-01-01                      1        0.284220              0
1           1                    DSP ELSS Tax Saver Fund 2024-01-01                      1        0.407139              0
2           1                         DSP Flexi Cap Fund 2024-01-01                      0        0.423435              0
3           1              Edelweiss ELSS Tax saver Fund 2024-01-01                      1        0.324978              0
4           1                   Edelweiss Flexi Cap Fund 2024-01-01                      1        0.329937              0
5           1         Franklin India ELSS Tax Saver Fund 2024-01-01                      1        0.458021              0
6           1              Franklin India Flexi Cap Fund 2024-01-01                      1        0.454566              0
7           1         Franklin India Focused Equity Fund 2024-01-01                      1        0.354144              0
8           1          Franklin India Opportunities Fund 2024-01-01                      1        0.692730              1
9           1                        HDFC ELSS Tax saver 2024-01-01                      1        0.563560              1
10          1                        HDFC Flexi Cap Fund 2024-01-01                      1        0.474064              0
11          1                          HDFC Focused Fund 2024-01-01                      1        0.532108              1
12          1                            HDFC Value Fund 2024-01-01                      1        0.385222              0
13          1                        HSBC Flexi Cap Fund 2024-01-01                      1        0.342354              0
14          1       ICICI Prudential ELSS Tax Saver Fund 2024-01-01                      1        0.292990              0
15          1  ICICI Prudential India Opportunities Fund 2024-01-01                      1        0.544100              1
16          1                    ITI ELSS Tax Saver Fund 2024-01-01                      1        0.528422              1
17          1                  Kotak ELSS Tax Saver Fund 2024-01-01                      1        0.446943              0
18          1                      LIC MF ELSS Tax Saver 2024-01-01                      1        0.405601              0
19          1                      LIC MF Flexi Cap Fund 2024-01-01                      1        0.464706              0

In [31]:
# ============================================================
# VALIDATE RF OOS PREDICTIONS
# ============================================================

print("Date range:")
print(
    rf_oos_df["month_date"].min(),
    "→",
    rf_oos_df["month_date"].max()
)

print()

print("Predictions by window:")
print(
    rf_oos_df
    .groupby("rf_window")
    .agg(
        observations=("scheme_name", "size"),
        funds=("scheme_name", "nunique"),
        mean_probability=("rf_probability", "mean"),
        min_probability=("rf_probability", "min"),
        max_probability=("rf_probability", "max")
    )
    .round(4)
)

Date range:
2024-01-01 00:00:00 → 2025-12-01 00:00:00

Predictions by window:
           observations  funds  mean_probability  min_probability  max_probability
rf_window
1                    96     32            0.4587           0.2842           0.7025
2                    97     33            0.4713           0.3457           0.6412
3                    99     33            0.4544           0.3417           0.5598
4                   126     60            0.5183           0.3377           0.5921
5                   220     75            0.4145           0.2057           0.5888
6                   226     76            0.5049           0.3575           0.5795
7                   235     81            0.5404           0.4696           0.5907
8                   247     85            0.4463           0.2432           0.6454

In [32]:
# ============================================================
# LEAKAGE CHECK
# ============================================================

leakage_check = rf_oos_df[
    rf_oos_df["month_date"] <= rf_oos_df["rf_train_end"]
]

print(
    "Predictions occurring inside training period:",
    len(leakage_check)
)

assert len(leakage_check) == 0

print("✓ No OOS prediction falls inside its training window.")

Predictions occurring inside training period: 0
✓ No OOS prediction falls inside its training window.

In [33]:
# ============================================================
# RF OOS — RANK FUNDS BY PREDICTED PROBABILITY
# ============================================================

rf_ranked_df = rf_oos_df.copy()

# Rank funds within each OOS month
rf_ranked_df["probability_rank"] = (
    rf_ranked_df
    .groupby("month_date")["rf_probability"]
    .rank(
        method="first",
        ascending=False
    )
)

# Number of funds available in each month
rf_ranked_df["funds_in_month"] = (
    rf_ranked_df
    .groupby("month_date")["scheme_name"]
    .transform("count")
)

# Percentile position
rf_ranked_df["probability_percentile"] = (
    1
    - (
        (rf_ranked_df["probability_rank"] - 1)
        / rf_ranked_df["funds_in_month"]
    )
)

display(
    rf_ranked_df[
        [
            "month_date",
            "scheme_name",
            "rf_probability",
            "probability_rank",
            "funds_in_month",
            "probability_percentile"
        ]
    ]
    .sort_values(
        ["month_date", "probability_rank"]
    )
    .head(50)
)

   month_date                                scheme_name  rf_probability  probability_rank  funds_in_month  probability_percentile
8  2024-01-01          Franklin India Opportunities Fund        0.692730               1.0              32                 1.00000
9  2024-01-01                        HDFC ELSS Tax saver        0.563560               2.0              32                 0.96875
15 2024-01-01  ICICI Prudential India Opportunities Fund        0.544100               3.0              32                 0.93750
20 2024-01-01          Motilal Oswal ELSS Tax Saver Fund        0.543086               4.0              32                 0.90625
11 2024-01-01                          HDFC Focused Fund        0.532108               5.0              32                 0.87500
16 2024-01-01                    ITI ELSS Tax Saver Fund        0.528422               6.0              32                 0.84375
24 2024-01-01           Parag Parikh ELSS Tax Saver Fund        0.521763               7.0              32                 0.81250
27 2024-01-01                     Shriram Flexi Cap Fund        0.483871               8.0              32                 0.78125
23 2024-01-01                  PGIM India Flexi Cap Fund        0.478627               9.0              32                 0.75000
10 2024-01-01                        HDFC Flexi Cap Fund        0.474064              10.0              32                 0.71875
19 2024-01-01                      LIC MF Flexi Cap Fund        0.464706              11.0              32                 0.68750
28 2024-01-01               Sundaram ELSS Tax Saver Fund        0.463447              12.0              32                 0.65625
5  2024-01-01         Franklin India ELSS Tax Saver Fund        0.458021              13.0              32                 0.62500
6  2024-01-01              Franklin India Flexi Cap Fund        0.454566              14.0              32                 0.59375
17 2024-01-01                  Kotak ELSS Tax Saver Fund        0.446943              15.0              32                 0.56250
25 2024-01-01                Parag Parikh Flexi Cap Fund        0.444614              16.0              32                 0.53125
22 2024-01-01                        Navi Flexi Cap Fund        0.435674              17.0              32                 0.50000
21 2024-01-01               Motilal Oswal Flexi Cap Fund        0.434817              18.0              32                 0.46875
30 2024-01-01                         UTI Flexi Cap Fund        0.423914              19.0              32                 0.43750
2  2024-01-01                         DSP Flexi Cap Fund        0.423435              20.0              32                 0.40625
26 2024-01-01                Shriram ELSS Tax Saver Fund        0.410358              21.0              32                 0.37500
1  2024-01-01                    DSP ELSS Tax Saver Fund        0.407139              22.0              32                 0.34375
18 2024-01-01                      LIC MF ELSS Tax Saver        0.405601              23.0              32                 0.31250
12 2024-01-01                            HDFC Value Fund        0.385222              24.0              32                 0.28125
7  2024-01-01         Franklin India Focused Equity Fund        0.354144              25.0              32                 0.25000
29 2024-01-01                    UTI ELSS Tax Saver Fund        0.351493              26.0              32                 0.21875
13 2024-01-01                        HSBC Flexi Cap Fund        0.342354              27.0              32                 0.18750
31 2024-01-01                             UTI Value Fund        0.336754              28.0              32                 0.15625
4  2024-01-01                   Edelweiss Flexi Cap Fund        0.329937              29.0              32                 0.12500
3  2024-01-01              Edelweiss ELSS Tax saver Fund        0.324978              30.0              32                 0.09375
14 2024-01-01       ICICI Prudential ELSS Tax Saver Fund        0.292990              31.0              32                 0.06250
0  2024-01-01                        Axis Flexi Cap Fund        0.284220              32.0              32                 0.03125
40 2024-02-01          Franklin India Opportunities Fund        0.697741               1.0              32                 1.00000
42 2024-02-01                        HDFC Flexi Cap Fund        0.616446               2.0              32                 0.96875
43 2024-02-01                          HDFC Focused Fund        0.581918               3.0              32                 0.93750
41 2024-02-01                        HDFC ELSS Tax saver        0.578336               4.0              32                 0.90625
47 2024-02-01  ICICI Prudential India Opportunities Fund        0.566858               5.0              32                 0.87500
48 2024-02-01                    ITI ELSS Tax Saver Fund        0.542965               6.0              32                 0.84375
52 2024-02-01          Motilal Oswal ELSS Tax Saver Fund        0.541805               7.0              32                 0.81250
57 2024-02-01                Parag Parikh Flexi Cap Fund        0.538952               8.0              32                 0.78125
37 2024-02-01         Franklin India ELSS Tax Saver Fund        0.528199               9.0              32                 0.75000
59 2024-02-01                     Shriram Flexi Cap Fund        0.526193              10.0              32                 0.71875
51 2024-02-01                      LIC MF Flexi Cap Fund        0.502646              11.0              32                 0.68750
38 2024-02-01              Franklin India Flexi Cap Fund        0.498004              12.0              32                 0.65625
53 2024-02-01               Motilal Oswal Flexi Cap Fund        0.490917              13.0              32                 0.62500
61 2024-02-01                    UTI ELSS Tax Saver Fund        0.488080              14.0              32                 0.59375
62 2024-02-01                         UTI Flexi Cap Fund        0.477330              15.0              32                 0.56250
54 2024-02-01                        Navi Flexi Cap Fund        0.476145              16.0              32                 0.53125
44 2024-02-01                            HDFC Value Fund        0.467217              17.0              32                 0.50000
58 2024-02-01                Shriram ELSS Tax Saver Fund        0.462051              18.0              32                 0.46875

In [34]:
# ============================================================
# XGBOOST — CONFIGURATION
# ============================================================

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV

xgb_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    (
        "model",
        XGBClassifier(
            objective="binary:logistic",
            eval_metric="logloss",
            random_state=RANDOM_STATE,
            n_jobs=-1,
            tree_method="hist"
        )
    )
])

xgb_param_grid = {
    "model__n_estimators": [200, 500],
    "model__max_depth": [3, 5],
    "model__learning_rate": [0.05, 0.10],
    "model__min_child_weight": [1, 5],
    "model__subsample": [0.8, 1.0],
    "model__colsample_bytree": [0.8, 1.0]
}

print("XGBoost configuration ready.")
print("Parameter combinations:",
      np.prod([
          len(v) for v in xgb_param_grid.values()
      ]))

XGBoost configuration ready.
Parameter combinations: 64

In [32]:
# # ============================================================
# # TEST XGBOOST CV ON WINDOW 1
# # ============================================================
#
# window_1 = rolling_train_data[0]
#
# X_train = window_1["X"]
# y_train = window_1["y"]
#
# xgb_grid = GridSearchCV(
#     estimator=xgb_pipeline,
#     param_grid=xgb_param_grid,
#     cv=cv,
#     scoring="roc_auc",
#     n_jobs=-1,
#     refit=True,
#     return_train_score=False
# )
#
# xgb_grid.fit(
#     X_train,
#     y_train
# )
#
# print("Window 1 XGBoost CV complete")
# print()
#
# print("Best parameters:")
# print(xgb_grid.best_params_)
#
# print()
#
# print(
#     f"Best CV ROC-AUC: "
#     f"{xgb_grid.best_score_:.4f}"
# )

In [35]:
# ============================================================
# XGBOOST — ROLLING OOS PREDICTIONS
# ============================================================

xgb_oos_predictions = []
xgb_window_results = []

print("=" * 70)
print("STARTING ROLLING XGBOOST OOS PREDICTION")
print("=" * 70)

for item in rolling_train_data:

    window_no = item["window"]

    # --------------------------------------------------------
    # TRAINING DATA
    # --------------------------------------------------------

    X_train = item["X"]
    y_train = item["y"]

    # --------------------------------------------------------
    # GET OOS DATES FROM rolling_windows_df
    # --------------------------------------------------------

    w = rolling_windows_df[
        rolling_windows_df["window"] == window_no
    ].iloc[0]

    # --------------------------------------------------------
    # GET OOS OBSERVATIONS FROM model_df
    # --------------------------------------------------------

    oos = model_df[
        (model_df["month_date"] >= w["oos_start"]) &
        (model_df["month_date"] <= w["oos_end"])
    ].copy()

    # Only features are required for prediction
    oos_predict = oos.dropna(
        subset=selected_features
    ).copy()

    if len(oos_predict) == 0:
        print(
            f"\nWindow {window_no}: "
            f"no usable OOS observations"
        )
        continue

    X_oos = oos_predict[selected_features]

    # --------------------------------------------------------
    # DISPLAY WINDOW
    # --------------------------------------------------------

    print("\n" + "=" * 70)

    print(f"Window {window_no}")

    print(
        f"TRAIN: {w['train_start'].strftime('%Y-%m')} "
        f"→ {w['train_end'].strftime('%Y-%m')}"
    )

    print(
        f"OOS:   {w['oos_start'].strftime('%Y-%m')} "
        f"→ {w['oos_end'].strftime('%Y-%m')}"
    )

    print(
        f"Training observations: {len(X_train):,}"
    )

    print(
        f"OOS observations:      {len(X_oos):,}"
    )

    # --------------------------------------------------------
    # 5-FOLD CV
    # --------------------------------------------------------

    xgb_grid = GridSearchCV(
        estimator=xgb_pipeline,
        param_grid=xgb_param_grid,
        cv=cv,
        scoring="roc_auc",
        n_jobs=-1,
        refit=True,
        return_train_score=False
    )

    xgb_grid.fit(
        X_train,
        y_train
    )

    print("\nBest parameters:")
    print(xgb_grid.best_params_)

    print(
        f"Best CV ROC-AUC: "
        f"{xgb_grid.best_score_:.4f}"
    )

    # --------------------------------------------------------
    # FINAL MODEL
    # --------------------------------------------------------

    # GridSearchCV with refit=True has already refitted
    # the best model on the complete training dataset.
    best_xgb = xgb_grid.best_estimator_

    # --------------------------------------------------------
    # OOS PROBABILITY
    # --------------------------------------------------------

    oos_predict["xgb_probability"] = (
        best_xgb.predict_proba(X_oos)[:, 1]
    )

    oos_predict["xgb_window"] = window_no

    # --------------------------------------------------------
    # STORE
    # --------------------------------------------------------

    xgb_oos_predictions.append(
        oos_predict[
            [
                "scheme_name",
                "month_date",
                TARGET,
                "xgb_probability",
                "xgb_window"
            ]
        ].copy()
    )

    xgb_window_results.append({
        "xgb_window": window_no,
        "train_start": w["train_start"],
        "train_end": w["train_end"],
        "oos_start": w["oos_start"],
        "oos_end": w["oos_end"],
        "training_observations": len(X_train),
        "oos_observations": len(X_oos),
        "best_cv_auc": xgb_grid.best_score_,
        "best_params": xgb_grid.best_params_
    })

    print(
        f"Mean P(outperformance): "
        f"{oos_predict['xgb_probability'].mean():.4f}"
    )


# ============================================================
# COMBINE ALL WINDOWS
# ============================================================

xgb_oos_df = pd.concat(
    xgb_oos_predictions,
    ignore_index=True
)

xgb_window_summary = pd.DataFrame(
    xgb_window_results
)

print("\n")
print("=" * 70)
print("XGBOOST OOS PREDICTION COMPLETE")
print("=" * 70)

print(
    "Total OOS predictions:",
    len(xgb_oos_df)
)

print(
    "Unique funds:",
    xgb_oos_df["scheme_name"].nunique()
)

print(
    "OOS months:",
    xgb_oos_df["month_date"].nunique()
)

print("\nDate range:")

print(
    xgb_oos_df["month_date"].min(),
    "→",
    xgb_oos_df["month_date"].max()
)

======================================================================
STARTING ROLLING XGBOOST OOS PREDICTION
======================================================================

======================================================================
Window 1
TRAIN: 2019-01 → 2023-12
OOS:   2024-01 → 2024-03
Training observations: 646
OOS observations:      96

Best parameters:
{'model__colsample_bytree': 0.8, 'model__learning_rate': 0.05, 'model__max_depth': 5, 'model__min_child_weight': 5, 'model__n_estimators': 500, 'model__subsample': 1.0}
Best CV ROC-AUC: 0.6230
Mean P(outperformance): 0.6265

======================================================================
Window 2
TRAIN: 2019-04 → 2024-03
OOS:   2024-04 → 2024-06
Training observations: 742
OOS observations:      97

Best parameters:
{'model__colsample_bytree': 0.8, 'model__learning_rate': 0.05, 'model__max_depth': 5, 'model__min_child_weight': 5, 'model__n_estimators': 500, 'model__subsample': 0.8}
Best CV ROC-AUC: 0.5834
Mean P(outperformance): 0.3079

======================================================================
Window 3
TRAIN: 2019-07 → 2024-06
OOS:   2024-07 → 2024-09
Training observations: 839
OOS observations:      99

Best parameters:
{'model__colsample_bytree': 0.8, 'model__learning_rate': 0.05, 'model__max_depth': 3, 'model__min_child_weight': 1, 'model__n_estimators': 200, 'model__subsample': 0.8}
Best CV ROC-AUC: 0.5397
Mean P(outperformance): 0.3795

======================================================================
Window 4
TRAIN: 2019-10 → 2024-09
OOS:   2024-10 → 2024-12
Training observations: 938
OOS observations:      126

Best parameters:
{'model__colsample_bytree': 0.8, 'model__learning_rate': 0.1, 'model__max_depth': 5, 'model__min_child_weight': 1, 'model__n_estimators': 200, 'model__subsample': 1.0}
Best CV ROC-AUC: 0.5496
Mean P(outperformance): 0.5835

======================================================================
Window 5
TRAIN: 2020-01 → 2024-12
OOS:   2025-01 → 2025-03
Training observations: 1,064
OOS observations:      220

Best parameters:
{'model__colsample_bytree': 1.0, 'model__learning_rate': 0.05, 'model__max_depth': 5, 'model__min_child_weight': 1, 'model__n_estimators': 200, 'model__subsample': 1.0}
Best CV ROC-AUC: 0.6206
Mean P(outperformance): 0.2486

======================================================================
Window 6
TRAIN: 2020-04 → 2025-03
OOS:   2025-04 → 2025-06
Training observations: 1,284
OOS observations:      226

Best parameters:
{'model__colsample_bytree': 1.0, 'model__learning_rate': 0.05, 'model__max_depth': 5, 'model__min_child_weight': 1, 'model__n_estimators': 200, 'model__subsample': 0.8}
Best CV ROC-AUC: 0.5315
Mean P(outperformance): 0.5427

======================================================================
Window 7
TRAIN: 2020-07 → 2025-06
OOS:   2025-07 → 2025-09
Training observations: 1,510
OOS observations:      235

Best parameters:
{'model__colsample_bytree': 1.0, 'model__learning_rate': 0.05, 'model__max_depth': 3, 'model__min_child_weight': 5, 'model__n_estimators': 200, 'model__subsample': 1.0}
Best CV ROC-AUC: 0.5477
Mean P(outperformance): 0.7528

======================================================================
Window 8
TRAIN: 2020-10 → 2025-09
OOS:   2025-10 → 2025-12
Training observations: 1,745
OOS observations:      247

Best parameters:
{'model__colsample_bytree': 1.0, 'model__learning_rate': 0.05, 'model__max_depth': 3, 'model__min_child_weight': 1, 'model__n_estimators': 200, 'model__subsample': 1.0}
Best CV ROC-AUC: 0.4906
Mean P(outperformance): 0.4776


======================================================================
XGBOOST OOS PREDICTION COMPLETE
======================================================================
Total OOS predictions: 1346
Unique funds: 85
OOS months: 24

Date range:
2024-01-01 00:00:00 → 2025-12-01 00:00:00

In [36]:
# ============================================================
# LIGHTGBM — CONFIGURATION
# ============================================================

from lightgbm import LGBMClassifier

lgbm_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    (
        "model",
        LGBMClassifier(
            objective="binary",
            random_state=RANDOM_STATE,
            n_jobs=-1,
            verbosity=-1
        )
    )
])

lgbm_param_grid = {
    "model__n_estimators": [200, 500],
    "model__num_leaves": [15, 31],
    "model__learning_rate": [0.05, 0.10],
    "model__max_depth": [-1, 5],
    "model__min_child_samples": [10, 20],
    "model__subsample": [0.8, 1.0],
    "model__colsample_bytree": [0.8, 1.0]
}

print("LightGBM configuration ready.")

print(
    "Parameter combinations:",
    np.prod([
        len(v)
        for v in lgbm_param_grid.values()
    ])
)

LightGBM configuration ready.
Parameter combinations: 128

In [37]:
# # ============================================================
# # TEST LIGHTGBM CV ON WINDOW 1
# # ============================================================
#
# window_1 = rolling_train_data[0]
#
# X_train = window_1["X"]
# y_train = window_1["y"]
#
# lgbm_grid = GridSearchCV(
#     estimator=lgbm_pipeline,
#     param_grid=lgbm_param_grid,
#     cv=cv,
#     scoring="roc_auc",
#     n_jobs=-1,
#     refit=True,
#     return_train_score=False
# )
#
# lgbm_grid.fit(
#     X_train,
#     y_train
# )
#
# print("Window 1 LightGBM CV complete")
# print()
#
# print("Best parameters:")
# print(lgbm_grid.best_params_)
#
# print()
#
# print(
#     f"Best CV ROC-AUC: "
#     f"{lgbm_grid.best_score_:.4f}"
# )

In [ ]:
# ============================================================
# LIGHTGBM — ROLLING 5-FOLD CV + OOS PREDICTIONS
# ============================================================

lgbm_oos_predictions = []
lgbm_window_results = []

print("=" * 70)
print("STARTING ROLLING LIGHTGBM OOS PREDICTION")
print("=" * 70)

for item in rolling_train_data:

    window_no = item["window"]

    # --------------------------------------------------------
    # TRAINING DATA
    # --------------------------------------------------------

    X_train = item["X"]
    y_train = item["y"]

    # --------------------------------------------------------
    # GET WINDOW / OOS DATES
    # --------------------------------------------------------

    w = rolling_windows_df[
        rolling_windows_df["window"] == window_no
    ].iloc[0]

    # --------------------------------------------------------
    # GET OOS DATA
    # --------------------------------------------------------

    oos = model_df[
        (model_df["month_date"] >= w["oos_start"]) &
        (model_df["month_date"] <= w["oos_end"])
    ].copy()

    # No imputation:
    # only observations with all selected features available
    oos_predict = oos.dropna(
        subset=selected_features
    ).copy()

    if len(oos_predict) == 0:
        print(
            f"\nWindow {window_no}: "
            f"no usable OOS observations"
        )
        continue

    X_oos = oos_predict[selected_features]

    # --------------------------------------------------------
    # DISPLAY WINDOW
    # --------------------------------------------------------

    print("\n" + "=" * 70)

    print(f"Window {window_no}")

    print(
        f"TRAIN: {w['train_start'].strftime('%Y-%m')} "
        f"→ {w['train_end'].strftime('%Y-%m')}"
    )

    print(
        f"OOS:   {w['oos_start'].strftime('%Y-%m')} "
        f"→ {w['oos_end'].strftime('%Y-%m')}"
    )

    print(
        f"Training observations: {len(X_train):,}"
    )

    print(
        f"OOS observations:      {len(X_oos):,}"
    )

    # --------------------------------------------------------
    # 5-FOLD CROSS-VALIDATION
    # --------------------------------------------------------

    lgbm_grid = GridSearchCV(
        estimator=lgbm_pipeline,
        param_grid=lgbm_param_grid,
        cv=cv,
        scoring="roc_auc",
        n_jobs=-1,
        refit=True,
        return_train_score=False
    )

    lgbm_grid.fit(
        X_train,
        y_train
    )

    # --------------------------------------------------------
    # BEST MODEL
    # --------------------------------------------------------

    best_lgbm = lgbm_grid.best_estimator_

    print("\nBest parameters:")
    print(lgbm_grid.best_params_)

    print(
        f"Best CV ROC-AUC: "
        f"{lgbm_grid.best_score_:.4f}"
    )

    # --------------------------------------------------------
    # OOS PROBABILITY
    # --------------------------------------------------------

    oos_predict["lgbm_probability"] = (
        best_lgbm.predict_proba(X_oos)[:, 1]
    )

    oos_predict["lgbm_window"] = window_no

    # --------------------------------------------------------
    # STORE OOS RESULTS
    # --------------------------------------------------------

    lgbm_oos_predictions.append(
        oos_predict[
            [
                "scheme_name",
                "month_date",
                TARGET,
                "lgbm_probability",
                "lgbm_window"
            ]
        ].copy()
    )

    # --------------------------------------------------------
    # STORE WINDOW SUMMARY
    # --------------------------------------------------------

    lgbm_window_results.append({
        "lgbm_window": window_no,
        "train_start": w["train_start"],
        "train_end": w["train_end"],
        "oos_start": w["oos_start"],
        "oos_end": w["oos_end"],
        "training_observations": len(X_train),
        "oos_observations": len(X_oos),
        "best_cv_auc": lgbm_grid.best_score_,
        "best_params": lgbm_grid.best_params_
    })

    print(
        f"Mean P(outperformance): "
        f"{oos_predict['lgbm_probability'].mean():.4f}"
    )


# ============================================================
# COMBINE ALL 8 WINDOWS
# ============================================================

lgbm_oos_df = pd.concat(
    lgbm_oos_predictions,
    ignore_index=True
)

lgbm_window_summary = pd.DataFrame(
    lgbm_window_results
)


# ============================================================
# FINAL SUMMARY
# ============================================================

print("\n")
print("=" * 70)
print("LIGHTGBM OOS PREDICTION COMPLETE")
print("=" * 70)

print(
    "Total OOS predictions:",
    len(lgbm_oos_df)
)

print(
    "Unique funds:",
    lgbm_oos_df["scheme_name"].nunique()
)

print(
    "OOS months:",
    lgbm_oos_df["month_date"].nunique()
)

print("\nDate range:")

print(
    lgbm_oos_df["month_date"].min(),
    "→",
    lgbm_oos_df["month_date"].max()
)

======================================================================
STARTING ROLLING LIGHTGBM OOS PREDICTION
======================================================================

======================================================================
Window 1
TRAIN: 2019-01 → 2023-12
OOS:   2024-01 → 2024-03
Training observations: 646
OOS observations:      96

Best parameters:
{'model__colsample_bytree': 1.0, 'model__learning_rate': 0.1, 'model__max_depth': -1, 'model__min_child_samples': 20, 'model__n_estimators': 200, 'model__num_leaves': 31, 'model__subsample': 0.8}
Best CV ROC-AUC: 0.6101
Mean P(outperformance): 0.6892

======================================================================
Window 2
TRAIN: 2019-04 → 2024-03
OOS:   2024-04 → 2024-06
Training observations: 742
OOS observations:      97

Best parameters:
{'model__colsample_bytree': 1.0, 'model__learning_rate': 0.1, 'model__max_depth': -1, 'model__min_child_samples': 20, 'model__n_estimators': 500, 'model__num_leaves': 31, 'model__subsample': 0.8}
Best CV ROC-AUC: 0.5883
Mean P(outperformance): 0.2811

======================================================================
Window 3
TRAIN: 2019-07 → 2024-06
OOS:   2024-07 → 2024-09
Training observations: 839
OOS observations:      99

Best parameters:
{'model__colsample_bytree': 1.0, 'model__learning_rate': 0.1, 'model__max_depth': -1, 'model__min_child_samples': 10, 'model__n_estimators': 200, 'model__num_leaves': 15, 'model__subsample': 0.8}
Best CV ROC-AUC: 0.5320
Mean P(outperformance): 0.3646

======================================================================
Window 4
TRAIN: 2019-10 → 2024-09
OOS:   2024-10 → 2024-12
Training observations: 938
OOS observations:      126

Best parameters:
{'model__colsample_bytree': 1.0, 'model__learning_rate': 0.05, 'model__max_depth': 5, 'model__min_child_samples': 20, 'model__n_estimators': 200, 'model__num_leaves': 31, 'model__subsample': 0.8}
Best CV ROC-AUC: 0.5497
Mean P(outperformance): 0.4578

======================================================================
Window 5
TRAIN: 2020-01 → 2024-12
OOS:   2025-01 → 2025-03
Training observations: 1,064
OOS observations:      220

Best parameters:
{'model__colsample_bytree': 0.8, 'model__learning_rate': 0.1, 'model__max_depth': -1, 'model__min_child_samples': 20, 'model__n_estimators': 200, 'model__num_leaves': 31, 'model__subsample': 0.8}
Best CV ROC-AUC: 0.6134
Mean P(outperformance): 0.2043

======================================================================
Window 6
TRAIN: 2020-04 → 2025-03
OOS:   2025-04 → 2025-06
Training observations: 1,284
OOS observations:      226

In [ ]:
# ============================================================
# COMBINE RF + XGBOOST + LIGHTGBM OOS PROBABILITIES
# ============================================================

rf_prob = rf_oos_df[
    [
        "scheme_name",
        "month_date",
        "rf_probability"
    ]
].copy()

xgb_prob = xgb_oos_df[
    [
        "scheme_name",
        "month_date",
        "xgb_probability"
    ]
].copy()

lgbm_prob = lgbm_oos_df[
    [
        "scheme_name",
        "month_date",
        "lgbm_probability"
    ]
].copy()


# ------------------------------------------------------------
# Merge
# ------------------------------------------------------------

ensemble_probability_df = (
    rf_prob
    .merge(
        xgb_prob,
        on=["scheme_name", "month_date"],
        how="inner",
        validate="one_to_one"
    )
    .merge(
        lgbm_prob,
        on=["scheme_name", "month_date"],
        how="inner",
        validate="one_to_one"
    )
)


# ------------------------------------------------------------
# Average probability
# ------------------------------------------------------------

ensemble_probability_df["average_probability"] = (
    ensemble_probability_df[
        [
            "rf_probability",
            "xgb_probability",
            "lgbm_probability"
        ]
    ].mean(axis=1)
)


# ------------------------------------------------------------
# Basic validation
# ------------------------------------------------------------

print("=" * 70)
print("ENSEMBLE PROBABILITY")
print("=" * 70)

print(
    "Total observations:",
    len(ensemble_probability_df)
)

print(
    "Unique funds:",
    ensemble_probability_df["scheme_name"].nunique()
)

print(
    "OOS months:",
    ensemble_probability_df["month_date"].nunique()
)

print(
    "\nDate range:",
    ensemble_probability_df["month_date"].min(),
    "→",
    ensemble_probability_df["month_date"].max()
)


# ------------------------------------------------------------
# Probability range check
# ------------------------------------------------------------

print("\nProbability ranges:")

print(
    ensemble_probability_df[
        [
            "rf_probability",
            "xgb_probability",
            "lgbm_probability",
            "average_probability"
        ]
    ].agg(
        ["min", "mean", "max"]
    ).round(4)
)


# ------------------------------------------------------------
# Display sample
# ------------------------------------------------------------

display(
    ensemble_probability_df[
        [
            "scheme_name",
            "month_date",
            "rf_probability",
            "xgb_probability",
            "lgbm_probability",
            "average_probability"
        ]
    ]
    .sort_values(
        ["month_date", "average_probability"],
        ascending=[True, False]
    )
    .head(30)
)

In [ ]:
# ============================================================
# RANK FUNDS BY AVERAGE PREDICTED PROBABILITY
# ============================================================

ensemble_ranked_df = ensemble_probability_df.copy()

# Rank within each month
ensemble_ranked_df["probability_rank"] = (
    ensemble_ranked_df
    .groupby("month_date")["average_probability"]
    .rank(
        method="first",
        ascending=False
    )
)

# Number of funds available that month
ensemble_ranked_df["funds_in_month"] = (
    ensemble_ranked_df
    .groupby("month_date")["scheme_name"]
    .transform("count")
)

# Cross-sectional percentile
ensemble_ranked_df["probability_percentile"] = (
    1
    -
    (
        ensemble_ranked_df["probability_rank"] - 1
    )
    /
    ensemble_ranked_df["funds_in_month"]
)

display(
    ensemble_ranked_df[
        [
            "month_date",
            "scheme_name",
            "rf_probability",
            "xgb_probability",
            "lgbm_probability",
            "average_probability",
            "probability_rank",
            "funds_in_month",
            "probability_percentile"
        ]
    ]
    .sort_values(
        ["month_date", "probability_rank"]
    )
    .head(50)
)

In [ ]:
# ============================================================
# MODEL RANK CORRELATION BY MONTH
# ============================================================

rank_check = ensemble_probability_df.copy()

for col in [
    "rf_probability",
    "xgb_probability",
    "lgbm_probability",
    "average_probability"
]:
    rank_check[col + "_rank"] = (
        rank_check
        .groupby("month_date")[col]
        .rank(
            method="average",
            ascending=False
        )
    )

rank_columns = [
    "rf_probability_rank",
    "xgb_probability_rank",
    "lgbm_probability_rank",
    "average_probability_rank"
]

rank_corr = (
    rank_check[rank_columns]
    .corr(method="spearman")
    .round(3)
)

display(rank_corr)

In [ ]:
# ============================================================
# PAPER-STYLE PORTFOLIO CONSTRUCTION
# 20 QUANTILE PORTFOLIOS
#
# Portfolio 0  = Top 5% predicted probability
# Portfolio 19 = Bottom 5%
# ============================================================

portfolio_df = ensemble_probability_df.copy()

# ------------------------------------------------------------
# Assign portfolio within each prediction month
# ------------------------------------------------------------
#
# rank 1 = highest predicted probability
#
# With 20 portfolios:
#   0 = top 5%
#   1 = next 5%
#   ...
#   19 = bottom 5%
#
portfolio_df["probability_rank"] = (
    portfolio_df
    .groupby("month_date")["average_probability"]
    .rank(
        method="first",
        ascending=False
    )
)

portfolio_df["funds_in_month"] = (
    portfolio_df
    .groupby("month_date")["scheme_name"]
    .transform("count")
)

portfolio_df["portfolio"] = (
    (
        (portfolio_df["probability_rank"] - 1)
        / portfolio_df["funds_in_month"]
        * 20
    )
    .astype(int)
    .clip(upper=19)
)

print("Portfolio construction complete.")

display(
    portfolio_df[
        [
            "month_date",
            "scheme_name",
            "average_probability",
            "probability_rank",
            "funds_in_month",
            "portfolio"
        ]
    ]
    .sort_values(
        ["month_date", "portfolio", "probability_rank"]
    )
    .head(50)
)

In [ ]:
# ============================================================
# PORTFOLIO SIZE CHECK
# ============================================================

portfolio_size_check = (
    portfolio_df
    .groupby(["month_date", "portfolio"])
    .size()
    .reset_index(name="fund_count")
)

display(
    portfolio_size_check
    .head(100)
)

In [ ]:
print("ensemble_ranked_df columns:")
print(ensemble_ranked_df.columns.tolist())

print("\nShape:", ensemble_ranked_df.shape)

display(ensemble_ranked_df.head())

In [ ]:
# ============================================================
# CREATE 20 PORTFOLIOS FROM AVERAGE PREDICTED PROBABILITY
# ============================================================

ensemble_ranked_df = ensemble_ranked_df.copy()

ensemble_ranked_df["portfolio"] = (
    ensemble_ranked_df
    .groupby("month_date")["average_probability"]
    .rank(
        method="first",
        ascending=False
    )
)

# Convert rank into 20 portfolios
ensemble_ranked_df["portfolio"] = (
    (
        (ensemble_ranked_df["portfolio"] - 1)
        /
        ensemble_ranked_df["funds_in_month"]
        * 20
    )
    .astype(int)
    .clip(upper=19)
)

print("Portfolio distribution:")
print(
    ensemble_ranked_df["portfolio"]
    .value_counts()
    .sort_index()
)

display(
    ensemble_ranked_df[
        [
            "month_date",
            "scheme_name",
            "average_probability",
            "probability_rank",
            "funds_in_month",
            "portfolio"
        ]
    ].head(20)
)

In [ ]:
check_month = ensemble_ranked_df["month_date"].min()

check = (
    ensemble_ranked_df[
        ensemble_ranked_df["month_date"] == check_month
    ]
    .sort_values("average_probability", ascending=False)
)

display(
    check[
        [
            "scheme_name",
            "average_probability",
            "probability_rank",
            "funds_in_month",
            "portfolio"
        ]
    ]
)

In [ ]:
# ============================================================
# PREPARE FINAL ML OOS PREDICTIONS FOR DATABASE
# ============================================================

ml_predictions_db = ensemble_ranked_df.copy()

# ------------------------------------------------------------
# Add target_month from model_df
# ------------------------------------------------------------

target_dates = model_df[
    [
        "scheme_name",
        "month_date",
        "target_month"
    ]
].drop_duplicates(
    ["scheme_name", "month_date"]
)

ml_predictions_db = ml_predictions_db.merge(
    target_dates,
    on=["scheme_name", "month_date"],
    how="left",
    validate="one_to_one"
)

# ------------------------------------------------------------
# Add actual target
# ------------------------------------------------------------

target_values = model_df[
    [
        "scheme_name",
        "month_date",
        TARGET
    ]
].drop_duplicates(
    ["scheme_name", "month_date"]
)

ml_predictions_db = ml_predictions_db.merge(
    target_values,
    on=["scheme_name", "month_date"],
    how="left",
    validate="one_to_one"
)

# ------------------------------------------------------------
# Select database columns
# ------------------------------------------------------------

ml_predictions_db = ml_predictions_db[
    [
        "scheme_name",
        "month_date",
        "target_month",
        TARGET,
        "rf_probability",
        "xgb_probability",
        "lgbm_probability",
        "average_probability",
        "probability_rank",
        "funds_in_month",
        "probability_percentile",
        "portfolio"
    ]
].copy()

# Rename target for database
ml_predictions_db = ml_predictions_db.rename(
    columns={
        TARGET: "outperforms_benchmark"
    }
)

# ------------------------------------------------------------
# Normalize dates
# ------------------------------------------------------------

ml_predictions_db["month_date"] = pd.to_datetime(
    ml_predictions_db["month_date"]
).dt.date

ml_predictions_db["target_month"] = pd.to_datetime(
    ml_predictions_db["target_month"]
).dt.date

# ------------------------------------------------------------
# Basic validation
# ------------------------------------------------------------

print("=" * 70)
print("FINAL ML PREDICTIONS")
print("=" * 70)

print("Rows:", len(ml_predictions_db))

print(
    "Unique funds:",
    ml_predictions_db["scheme_name"].nunique()
)

print(
    "Prediction months:",
    ml_predictions_db["month_date"].nunique()
)

print(
    "Target months:",
    ml_predictions_db["target_month"].nunique()
)

print("\nMissing values:")
print(
    ml_predictions_db.isna().sum()
)

display(ml_predictions_db.head(20))

In [ ]:
# ============================================================
# PROBABILITY VALIDATION
# ============================================================

probability_columns = [
    "rf_probability",
    "xgb_probability",
    "lgbm_probability",
    "average_probability"
]

print(
    ml_predictions_db[probability_columns]
    .agg(["min", "mean", "max"])
    .round(6)
)

# Check probability bounds
for col in probability_columns:

    bad = (
        (ml_predictions_db[col] < 0) |
        (ml_predictions_db[col] > 1)
    ).sum()

    print(
        f"{col}: invalid probabilities = {bad}"
    )

In [ ]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:Password%40123@localhost:5432/mfdb"
)

print(type(engine))

In [ ]:
# ============================================================
# WRITE TO POSTGRESQL
# ============================================================

from sqlalchemy import text

with engine.begin() as connection:

    # Make reruns safe
    connection.execute(
        text("""
            DELETE FROM mf200.ml_oos_predictions_seq
            WHERE month_date BETWEEN :start_date AND :end_date
        """),
        {
            "start_date": ml_predictions_db["month_date"].min(),
            "end_date": ml_predictions_db["month_date"].max()
        }
    )

ml_predictions_db.to_sql(
    "ml_oos_predictions_seq",
    engine,
    schema="mf200",
    if_exists="append",
    index=False,
    method="multi",
    chunksize=1000
)

print(
    f"✓ Saved {len(ml_predictions_db):,} rows "
    "to mf200.ml_oos_predictions"
)