# Random Forest with IQR Anomaly Treatment

This notebook is the anomaly-treatment counterpart to `10B_RF_model(3).ipynb`.

**Design:** same 22 IC-selected features, 60-month rolling training window, 3-month OOS period, 5-fold K-Fold CV, RF hyperparameter grid, COVID exclusion, and 2019–2025 model period. The modeling change is Tukey IQR clipping (`1.5 × IQR`) inside the sklearn pipeline.

The IQR thresholds are learned from training data only. Because the transformer is inside `GridSearchCV`, each CV fold learns its thresholds only from that fold's training portion. The refitted pipeline then learns thresholds from the full rolling training window before OOS prediction. OOS observations are never used to estimate anomaly bounds.

**Important:** IQR anomaly treatment is an intentional methodological adaptation; it is not specified as part of the original paper's methodology.

## IQR-Based Anomaly Treatment

Financial datasets can contain unusually extreme observations that may be caused by data errors or abnormal values. To reduce the influence of such extreme observations, we apply the **Interquartile Range (IQR) method** to the 22 selected model features.

For each feature:

- **Q1** = 25th percentile
- **Q3** = 75th percentile
- **IQR** = Q3 − Q1

The lower and upper IQR boundaries are defined as:

- Lower bound = Q1 − 1.5 × IQR
- Upper bound = Q3 + 1.5 × IQR

Observations below the lower bound or above the upper bound are considered potential anomalies.

Instead of deleting these observations, we **clip (winsorize) them to the corresponding IQR boundary**. This preserves the observation and the number of training samples while reducing the influence of extreme feature values.

### Why is IQR applied inside the ML pipeline?

The IQR thresholds are estimated using **training data only**.

The IQR transformer is placed inside the sklearn Pipeline before the Random Forest model. During 5-fold cross-validation, each training fold independently estimates its Q1, Q3, and IQR values. Therefore, information from the validation fold is not used to determine the anomaly thresholds.

After hyperparameter selection, the pipeline is refitted using the complete rolling training window. The resulting IQR thresholds are then applied to the OOS observations.

Thus, **OOS data is never used to determine the anomaly boundaries**, avoiding data leakage.

### Important methodological note

IQR-based anomaly treatment is an **intentional methodological adaptation for this study**. The original Wu et al. (2025) paper does not specify IQR-based anomaly treatment. It is introduced here to reduce the influence of extreme observations in the Indian mutual-fund dataset.

In [35]:
# IMPORTANT METHODOLOGICAL NOTE:
#
# CRISIL data is used only to identify the Nifty 500 TRI
# fund universe and map CRISIL fund names to the corresponding
# Direct Growth MF scheme names.
#
# CRISIL observation dates are NOT used as a temporal filter.
# Once a fund is uniquely mapped to the Nifty 500 TRI universe,
# all available feature observations for that fund from
# 2013–2019 are retained.
#
# Therefore, this is a fund-level benchmark-universe mapping,
# rather than a month-by-month historical benchmark-membership
# reconstruction.

In [36]:
# ============================================================
# FINAL 22 IC-SELECTED FEATURES
# ============================================================

SELECTED_FEATURES_IC = [
    "t_hml_750",
    "t_hml_250",
    "t_hml_180",
    "ir_p1y",
    "sr_p1y",
    "ir_p3y",
    "t_hml_120",
    "t_const_250",
    "ir_p6m",
    "sr_p3y",
    "t_hml_90",
    "t_const_180",
    "sr_p6m",
    "const_250",
    "const_180",
    "const_90",
    "t_const_90",
    "t_umd_750",
    "const_120",
    "t_const_120",
    "t_smb_750",
    "r2_750",
]

In [37]:
from pathlib import Path

RUN_TIMESTAMP_FILE = Path("D:\\PycharmProjects\\mf-ml\\run_timestamp.txt")

if not RUN_TIMESTAMP_FILE.exists():
    raise FileNotFoundError(
        f"Run timestamp file not found: {RUN_TIMESTAMP_FILE.resolve()}"
    )

RUN_TIMESTAMP = RUN_TIMESTAMP_FILE.read_text().strip()

if not RUN_TIMESTAMP:
    raise ValueError("run_timestamp.txt is empty")

print("Run timestamp:", RUN_TIMESTAMP)

Run timestamp: 20260912_003517

In [38]:
# ============================================================
# RANDOM FOREST + IQR ANOMALY TREATMENT
# CONFIGURATION
# ============================================================

import numpy as np
import pandas as pd

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV

RANDOM_STATE = 42
TARGET = "outperforms_benchmark"
IQR_MULTIPLIER = 1.5

# ------------------------------------------------------------
# FINAL 22 IC-SELECTED FEATURES
# ------------------------------------------------------------
selected_features = SELECTED_FEATURES_IC.copy()
DROP_FEATURES = []
rf_features = [f for f in selected_features if f not in DROP_FEATURES]

unknown_drops = [f for f in DROP_FEATURES if f not in selected_features]
if unknown_drops:
    raise ValueError(
        f"DROP_FEATURES contains features that are not in selected_features: {unknown_drops}"
    )

print("=" * 70)
print("RANDOM FOREST + IQR CONFIGURATION")
print("=" * 70)
print(f"Original IC-selected features : {len(selected_features)}")
print(f"Dropped features              : {len(DROP_FEATURES)}")
print(f"Features used by RF           : {len(rf_features)}")
print(f"IQR multiplier                : {IQR_MULTIPLIER}")
print("\nFeatures used:")
for i, f in enumerate(rf_features, 1):
    print(f"{i:2d}. {f}")

# ============================================================
# IQR ANOMALY CLIPPER
# ============================================================

class IQRAnomalyClipper(BaseEstimator, TransformerMixin):
    """Clip values outside Tukey IQR fences learned from fit data only."""

    def __init__(self, multiplier=1.5):
        self.multiplier = multiplier

    def fit(self, X, y=None):
        if isinstance(X, pd.DataFrame):
            X_df = X.copy()
        else:
            X_df = pd.DataFrame(X)

        self.feature_names_in_ = np.asarray(X_df.columns, dtype=object)
        self.n_features_in_ = X_df.shape[1]
        self.q1_ = X_df.quantile(0.25)
        self.q3_ = X_df.quantile(0.75)
        self.iqr_ = self.q3_ - self.q1_
        self.lower_bounds_ = self.q1_ - self.multiplier * self.iqr_
        self.upper_bounds_ = self.q3_ + self.multiplier * self.iqr_
        return self

    def transform(self, X):
        if isinstance(X, pd.DataFrame):
            X_df = X.copy()
            X_df.columns = self.feature_names_in_
        else:
            X_df = pd.DataFrame(X, columns=self.feature_names_in_)

        X_clipped = X_df.clip(
            lower=self.lower_bounds_,
            upper=self.upper_bounds_,
            axis="columns"
        )
        return X_clipped.to_numpy()

======================================================================
RANDOM FOREST + IQR CONFIGURATION
======================================================================
Original IC-selected features : 22
Dropped features              : 0
Features used by RF           : 22
IQR multiplier                : 1.5

Features used:
 1. t_hml_750
 2. t_hml_250
 3. t_hml_180
 4. ir_p1y
 5. sr_p1y
 6. ir_p3y
 7. t_hml_120
 8. t_const_250
 9. ir_p6m
10. sr_p3y
11. t_hml_90
12. t_const_180
13. sr_p6m
14. const_250
15. const_180
16. const_90
17. t_const_90
18. t_umd_750
19. const_120
20. t_const_120
21. t_smb_750
22. r2_750

In [39]:
# ============================================================
# PREPARE MODEL DATA
# ============================================================

import os
import pandas as pd
from sqlalchemy import create_engine, text


# ------------------------------------------------------------
# DATABASE CONNECTION
# ------------------------------------------------------------
# ============================================================
# 1. DATABASE CONNECTION
# ============================================================

from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:Password%40123@localhost:5432/mfdb"
)

print(type(engine))

print("Database engine created.")

SOURCE_TABLE = f"feature_matrix_2013_2019_{RUN_TIMESTAMP}"

# ============================================================
# 1. LOAD FEATURE MATRIX
# ============================================================

FEATURE_SQL = f"""
SELECT *
FROM mf200.{SOURCE_TABLE}
ORDER BY month_date, scheme_name
"""

features_df = pd.read_sql(
    text(FEATURE_SQL),
    engine
)

features_df["month_date"] = pd.to_datetime(
    features_df["month_date"],
    errors="coerce"
)

features_df["performance_date"] = pd.to_datetime(
    features_df["performance_date"],
    errors="coerce"
)


print("=" * 70)
print("FEATURE MATRIX")
print("=" * 70)

print("Shape:", features_df.shape)

print(
    "Date range:",
    features_df["month_date"].min(),
    "→",
    features_df["month_date"].max()
)

print(
    "Unique funds:",
    features_df["scheme_name"].nunique()
)

display(features_df.head())

<class 'sqlalchemy.engine.base.Engine'>
Database engine created.
======================================================================
FEATURE MATRIX
======================================================================
Shape: (140365, 46)
Date range: 2013-01-01 00:00:00 → 2019-12-01 00:00:00
Unique funds: 3727

,scheme_name,month_date,performance_date,tna,vol_flows,const_90,const_120,const_180,const_250,const_750,...,t_umd_120,t_umd_180,t_umd_250,t_umd_750,ir_p6m,ir_p1y,ir_p3y,sr_p6m,sr_p1y,sr_p3y
0,Aditya Birla Sun Life Arbitrage Fund - Growth ...,2013-01-01,2013-01-31,None,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aditya Birla Sun Life Asset Allocation-Conserv...,2013-01-01,2013-01-31,None,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aditya Birla Sun Life Asset Allocation - Aggre...,2013-01-01,2013-01-31,None,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Aditya Birla Sun Life Asset Allocation - Moder...,2013-01-01,2013-01-31,None,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Aditya Birla Sun Life Banking & PSU Debt Fund-...,2013-01-01,2013-01-31,None,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
import pandas as pd
import re

# ============================================================
# 1. Load CRISIL Nifty 500 schemes
# ============================================================

crisil_sql = """
SELECT DISTINCT
    LOWER(TRIM("schemeName")) AS crisil_scheme_name
FROM mf200.crisil_fund_daily_raw
WHERE benchmark = 'Nifty 500 TRI'
  AND NULLIF(TRIM("schemeName"), '') IS NOT NULL;
"""

crisil_nifty500 = pd.read_sql(crisil_sql, engine)

print("CRISIL Nifty 500 schemes:", len(crisil_nifty500))

CRISIL Nifty 500 schemes: 169

In [41]:


# ============================================================
# 2. Load Direct Growth universe
# ============================================================

direct_growth_sql = """
SELECT DISTINCT
    scheme_code,
    scheme_name
FROM mf100.direct_growth_nav;
"""

direct_growth = pd.read_sql(direct_growth_sql, engine)

print("Direct Growth schemes:", len(direct_growth))


# ============================================================
# 3. Normalize names for matching
# ============================================================

direct_growth["scheme_name_lower"] = (
    direct_growth["scheme_name"]
    .str.strip()
    .str.lower()
)


# ============================================================
# 4. Find candidate matches
#    Equivalent to:
#
#    LOWER(d.scheme_name) LIKE '%' || c.crisil_scheme_name || '%'
# ============================================================

candidate_matches = []

for crisil_name in crisil_nifty500["crisil_scheme_name"]:

    matches = direct_growth[
        direct_growth["scheme_name_lower"].str.contains(
            re.escape(crisil_name),
            regex=True,
            na=False
        )
    ].copy()

    if len(matches) > 0:
        matches["crisil_scheme_name"] = crisil_name
        candidate_matches.append(matches)


# Combine all candidates
candidate_matches = pd.concat(
    candidate_matches,
    ignore_index=True
)

print("Candidate matches:", len(candidate_matches))

Direct Growth schemes: 5028
Candidate matches: 154

In [42]:
candidate_matches

,scheme_code,scheme_name,scheme_name_lower,crisil_scheme_name
0,119544,Aditya Birla Sun Life ELSS Tax Saver Fund - Gr...,aditya birla sun life elss tax saver fund - gr...,aditya birla sun life elss tax saver fund
1,120564,Aditya Birla Sun Life Flexi Cap Fund - Growth ...,aditya birla sun life flexi cap fund - growth ...,aditya birla sun life flexi cap fund
2,119564,Aditya Birla Sun Life Focused Fund - Growth - ...,aditya birla sun life focused fund - growth - ...,aditya birla sun life focused fund
3,119659,Aditya Birla Sun Life Value Fund - Growth - Di...,aditya birla sun life value fund - growth - di...,aditya birla sun life value fund
4,151368,Axis Business Cycles Fund - Direct Plan - Growth,axis business cycles fund - direct plan - growth,axis business cycles fund
...,...,...,...,...
149,151905,Union Innovation & Opportunities Fund - Direct...,union innovation & opportunities fund - direct...,union innovation & opportunities fund
150,120715,UTI ELSS Tax Saver Fund - Direct Plan - Growth...,uti elss tax saver fund - direct plan - growth...,uti elss tax saver fund
151,149091,UTI Focused Fund - Direct Plan - Growth Option,uti focused fund - direct plan - growth option,uti focused fund
152,152087,UTI Innovation Fund - Direct Plan - Growth Option,uti innovation fund - direct plan - growth option,uti innovation fund
153,120751,UTI Value Fund - Direct Plan - Growth Option,uti value fund - direct plan - growth option,uti value fund

In [43]:
# ============================================================
# IDENTIFY DIRECT GROWTH FUNDS CLASSIFIED AS NIFTY 500 TRI
# ============================================================

import pandas as pd
import re

# ------------------------------------------------------------
# 1. Load CRISIL fund names currently classified as Nifty 500 TRI
# ------------------------------------------------------------

crisil_sql = """
SELECT DISTINCT
    LOWER(TRIM("schemeName")) AS crisil_scheme_name
FROM mf200.crisil_fund_daily_raw
WHERE benchmark = 'Nifty 500 TRI'
  AND NULLIF(TRIM("schemeName"), '') IS NOT NULL
"""

crisil_nifty500 = pd.read_sql(
    text(crisil_sql),
    engine
)

print("CRISIL Nifty 500 schemes:", len(crisil_nifty500))


# ------------------------------------------------------------
# 2. Load Direct Growth MF universe
# ------------------------------------------------------------

direct_growth_sql = """
SELECT DISTINCT
    scheme_code,
    scheme_name
FROM mf100.direct_growth_nav
"""

direct_growth = pd.read_sql(
    text(direct_growth_sql),
    engine
)

print("Direct Growth schemes:", len(direct_growth))


# ------------------------------------------------------------
# 3. Normalize MF scheme names
# ------------------------------------------------------------

direct_growth["scheme_name_lower"] = (
    direct_growth["scheme_name"]
    .str.strip()
    .str.lower()
)


# ------------------------------------------------------------
# 4. Match CRISIL names to MF Direct Growth names
#
# CRISIL:
#     "Axis Flexi Cap Fund"
#
# MF:
#     "Axis Flexi Cap Fund - Growth - Direct Plan"
#
# Therefore CRISIL name is searched inside MF scheme name.
# ------------------------------------------------------------

candidate_matches = []

for crisil_name in crisil_nifty500["crisil_scheme_name"]:

    matches = direct_growth[
        direct_growth["scheme_name_lower"].str.contains(
            re.escape(crisil_name),
            regex=True,
            na=False
        )
    ].copy()

    if len(matches) > 0:
        matches["crisil_scheme_name"] = crisil_name
        candidate_matches.append(matches)


candidate_matches = pd.concat(
    candidate_matches,
    ignore_index=True
)


# ------------------------------------------------------------
# 5. Keep only UNIQUE mappings
#
# If one CRISIL name maps to multiple MF schemes,
# do not automatically choose one.
# ------------------------------------------------------------

match_counts = (
    candidate_matches
    .groupby("crisil_scheme_name")["scheme_code"]
    .nunique()
    .reset_index(name="candidate_count")
)


mapped_funds = candidate_matches.merge(
    match_counts,
    on="crisil_scheme_name",
    how="left"
)


mapped_funds = mapped_funds[
    mapped_funds["candidate_count"] == 1
].copy()


# ------------------------------------------------------------
# 6. Add benchmark/mapping metadata
# ------------------------------------------------------------

mapped_funds["benchmark"] = "Nifty 500 TRI"
mapped_funds["mapping_method"] = "CRISIL_NAME_CONTAINS"
mapped_funds["mapping_status"] = "AUTO_UNIQUE"


mapped_funds = mapped_funds[
    [
        "scheme_code",
        "scheme_name",
        "crisil_scheme_name",
        "benchmark",
        "mapping_method",
        "mapping_status"
    ]
].drop_duplicates()


# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

print("=" * 70)
print("NIFTY 500 TRI FUND MAPPING")
print("=" * 70)

print("CRISIL Nifty 500 names :", len(crisil_nifty500))
print("Candidate mappings      :", len(candidate_matches))
print("Unique mapped funds     :", mapped_funds["scheme_name"].nunique())

print("\nMapped funds:")
display(mapped_funds.head())

CRISIL Nifty 500 schemes: 169
Direct Growth schemes: 5028
======================================================================
NIFTY 500 TRI FUND MAPPING
======================================================================
CRISIL Nifty 500 names : 169
Candidate mappings      : 154
Unique mapped funds     : 140

Mapped funds:

,scheme_code,scheme_name,crisil_scheme_name,benchmark,mapping_method,mapping_status
0,119544,Aditya Birla Sun Life ELSS Tax Saver Fund - Gr...,aditya birla sun life elss tax saver fund,Nifty 500 TRI,CRISIL_NAME_CONTAINS,AUTO_UNIQUE
1,120564,Aditya Birla Sun Life Flexi Cap Fund - Growth ...,aditya birla sun life flexi cap fund,Nifty 500 TRI,CRISIL_NAME_CONTAINS,AUTO_UNIQUE
2,119564,Aditya Birla Sun Life Focused Fund - Growth - ...,aditya birla sun life focused fund,Nifty 500 TRI,CRISIL_NAME_CONTAINS,AUTO_UNIQUE
3,119659,Aditya Birla Sun Life Value Fund - Growth - Di...,aditya birla sun life value fund,Nifty 500 TRI,CRISIL_NAME_CONTAINS,AUTO_UNIQUE
4,151368,Axis Business Cycles Fund - Direct Plan - Growth,axis business cycles fund,Nifty 500 TRI,CRISIL_NAME_CONTAINS,AUTO_UNIQUE

In [44]:
# ============================================================
# FILTER FEATURE MATRIX TO NIFTY 500 FUNDS
# ============================================================

nifty500_scheme_names = (
    mapped_funds["scheme_name"]
    .dropna()
    .drop_duplicates()
    .tolist()
)


feature_df = features_df[
    features_df["scheme_name"].isin(nifty500_scheme_names)
].copy()


# ------------------------------------------------------------
# Add benchmark metadata
# ------------------------------------------------------------

feature_df["benchmark"] = "Nifty 500 TRI"


print("=" * 70)
print("NIFTY 500 FEATURE MATRIX")
print("=" * 70)

print("Rows :", len(feature_df))
print("Funds:", feature_df["scheme_name"].nunique())
print(
    "Date range:",
    feature_df["month_date"].min(),
    "→",
    feature_df["month_date"].max()
)

print(
    "\nMonths:",
    feature_df["month_date"].nunique()
)

display(feature_df.head())

======================================================================
NIFTY 500 FEATURE MATRIX
======================================================================
Rows : 3970
Funds: 62
Date range: 2013-01-01 00:00:00 → 2019-12-01 00:00:00

Months: 84

,scheme_name,month_date,performance_date,tna,vol_flows,const_90,const_120,const_180,const_250,const_750,...,t_umd_180,t_umd_250,t_umd_750,ir_p6m,ir_p1y,ir_p3y,sr_p6m,sr_p1y,sr_p3y,benchmark
13,Aditya Birla Sun Life ELSS Tax Saver Fund - Gr...,2013-01-01,2013-01-31,None,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nifty 500 TRI
15,Aditya Birla Sun Life Flexi Cap Fund - Growth ...,2013-01-01,2013-01-31,None,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nifty 500 TRI
16,Aditya Birla Sun Life Focused Fund - Growth - ...,2013-01-01,2013-01-31,None,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nifty 500 TRI
47,Aditya Birla Sun Life Value Fund - Growth - Di...,2013-01-01,2013-01-31,None,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nifty 500 TRI
51,Axis ELSS Tax Saver Fund - Direct Plan - Growt...,2013-01-01,2013-01-31,None,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nifty 500 TRI

In [46]:
# ============================================================
# 2. LOAD TARGET DATA
# ============================================================

TARGET_SQL = """
SELECT *
FROM mf200.fund_monthly_outperformance_targets20260912_003517
ORDER BY scheme_name, target_month
"""

target_df = pd.read_sql(
    text(TARGET_SQL),
    engine
)

# ------------------------------------------------------------
# DATE CONVERSION
# ------------------------------------------------------------

target_df["month_date"] = pd.to_datetime(
    target_df["month_date"],
    errors="coerce"
)

target_df["target_month"] = pd.to_datetime(
    target_df["target_month"],
    errors="coerce"
)


print("=" * 70)
print("TARGET DATA")
print("=" * 70)

print("Shape:", target_df.shape)

print(
    "Date range:",
    target_df["month_date"].min(),
    "→",
    target_df["month_date"].max()
)

print("\nTarget distribution:")
print(
    target_df["outperforms_benchmark"]
    .value_counts(dropna=False)
)

display(target_df.head())

======================================================================
TARGET DATA
======================================================================
Shape: (252165, 13)
Date range: 2006-04-01 00:00:00 → 2026-06-01 00:00:00

Target distribution:
outperforms_benchmark
0    137409
1    114756
Name: count, dtype: int64

,scheme_name,month_date,current_monthly_return_percent,current_benchmark_monthly_return_percent,target_month,trade_month_end,benchmark_name,benchmark_month_end,monthly_return_percent,benchmark_monthly_return_percent,excess_return_percent,outperforms_benchmark,loaded_at
0,360 ONE Balanced Hybrid Fund- Direct Plan - Gr...,2023-10-01,NaN,-2.774442,2023-11-01,2023-11-30,Nifty 500 TRI,2023-11-30,4.023296,7.150967,-3.127671,0,2026-09-12 14:13:31.783666+00:00
1,360 ONE Balanced Hybrid Fund- Direct Plan - Gr...,2023-11-01,4.023296,7.150967,2023-12-01,2023-12-29,Nifty 500 TRI,2023-12-31,4.127636,8.013306,-3.885670,0,2026-09-12 14:13:31.783666+00:00
2,360 ONE Balanced Hybrid Fund- Direct Plan - Gr...,2023-12-01,4.127636,8.013306,2024-01-01,2024-01-31,Nifty 500 TRI,2024-01-31,0.888470,1.950733,-1.062263,0,2026-09-12 14:13:31.783666+00:00
3,360 ONE Balanced Hybrid Fund- Direct Plan - Gr...,2024-01-01,0.888470,1.950733,2024-02-01,2024-02-29,Nifty 500 TRI,2024-02-29,1.731944,1.574078,0.157866,1,2026-09-12 14:13:31.783666+00:00
4,360 ONE Balanced Hybrid Fund- Direct Plan - Gr...,2024-02-01,1.731944,1.574078,2024-03-01,2024-03-31,Nifty 500 TRI,2024-03-31,0.119894,0.000032,0.119862,1,2026-09-12 14:13:31.783666+00:00

In [47]:
# ============================================================
# MERGE FEATURE MATRIX WITH TARGET
# ============================================================

print("=" * 70)
print("MERGING FEATURE DATA WITH TARGET")
print("=" * 70)

print("Feature rows :", len(feature_df))
print("Feature funds:", feature_df["scheme_name"].nunique())

print("\nTarget rows  :", len(target_df))
print("Target funds :", target_df["scheme_name"].nunique())


# ------------------------------------------------------------
# Target columns to bring into feature matrix
# ------------------------------------------------------------

target_cols = [
    "scheme_name",
    "month_date",
    "target_month",
    "outperforms_benchmark",
    "excess_return_percent",
    "current_monthly_return_percent",
    "current_benchmark_monthly_return_percent"
]


# ------------------------------------------------------------
# Merge
# ------------------------------------------------------------

model_df = feature_df.merge(
    target_df[target_cols],
    on=["scheme_name", "month_date"],
    how="left",
    validate="one_to_one"
)


print("\nAfter merge:")
print("Rows :", len(model_df))
print("Funds:", model_df["scheme_name"].nunique())

print("\nTarget availability:")
print(
    model_df["outperforms_benchmark"]
    .value_counts(dropna=False)
)

display(model_df.head())

======================================================================
MERGING FEATURE DATA WITH TARGET
======================================================================
Feature rows : 3970
Feature funds: 62

Target rows  : 252165
Target funds : 4857

After merge:
Rows : 3970
Funds: 62

Target availability:
outperforms_benchmark
1.0    2051
0.0    1918
NaN       1
Name: count, dtype: int64

,scheme_name,month_date,performance_date,tna,vol_flows,const_90,const_120,const_180,const_250,const_750,...,ir_p3y,sr_p6m,sr_p1y,sr_p3y,benchmark,target_month,outperforms_benchmark,excess_return_percent,current_monthly_return_percent,current_benchmark_monthly_return_percent
0,Aditya Birla Sun Life ELSS Tax Saver Fund - Gr...,2013-01-01,2013-01-31,None,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Nifty 500 TRI,2013-02-01,1.0,0.472700,NaN,1.111116
1,Aditya Birla Sun Life Flexi Cap Fund - Growth ...,2013-01-01,2013-01-31,None,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Nifty 500 TRI,2013-02-01,0.0,-0.703646,NaN,1.111116
2,Aditya Birla Sun Life Focused Fund - Growth - ...,2013-01-01,2013-01-31,None,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Nifty 500 TRI,2013-02-01,1.0,0.011050,NaN,1.111116
3,Aditya Birla Sun Life Value Fund - Growth - Di...,2013-01-01,2013-01-31,None,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Nifty 500 TRI,2013-02-01,1.0,0.696191,NaN,1.111116
4,Axis ELSS Tax Saver Fund - Direct Plan - Growt...,2013-01-01,2013-01-31,None,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Nifty 500 TRI,2013-02-01,1.0,1.946799,NaN,1.111116

In [48]:
# # ============================================================
# # JOIN FEATURES + TARGET
# # ============================================================
#
# model_df = features_df.merge(
#     target_df[
#         [
#             "scheme_name",
#             "month_date",
#             "target_month",
#             "outperforms_benchmark",
#             "excess_return_percent",
#             "current_monthly_return_percent",
#             "current_benchmark_monthly_return_percent"
#         ]
#     ],
#     on=[
#         "scheme_name",
#         "month_date"
#     ],
#     how="left"
# )
#
# model_df = model_df.merge(
#     nifty500_fund_months,
#     on=["scheme_name", "month_date"],
#     how="inner"
# )
#
# print("=" * 70)
# print("MODEL DATA")
# print("=" * 70)
#
# print("Shape:", model_df.shape)
#
# print(
#     "Feature month:",
#     model_df["month_date"].min(),
#     "→",
#     model_df["month_date"].max()
# )
#
# print(
#     "Target month:",
#     model_df["target_month"].min(),
#     "→",
#     model_df["target_month"].max()
# )

In [49]:
# ============================================================
# VALIDATE TARGET TIMING
# ============================================================

model_df["expected_target_month"] = (
    model_df["month_date"] +
    pd.DateOffset(months=1)
)

# ------------------------------------------------------------
# 1. Missing target
# ------------------------------------------------------------

missing_target = model_df["target_month"].isna()

# ------------------------------------------------------------
# 2. Target exists and timing is correct
# ------------------------------------------------------------

target_exists = ~missing_target

timing_ok = (
    target_exists &
    (
        model_df["target_month"]
        == model_df["expected_target_month"]
    )
)

# ------------------------------------------------------------
# 3. Target exists but timing is wrong
# ------------------------------------------------------------

timing_wrong = (
    target_exists &
    (
        model_df["target_month"]
        != model_df["expected_target_month"]
    )
)


print("=" * 70)
print("TARGET TIMING VALIDATION")
print("=" * 70)

print(f"Correct target timing : {timing_ok.sum():,}")
print(f"Missing target        : {missing_target.sum():,}")
print(f"Wrong target timing   : {timing_wrong.sum():,}")


# ------------------------------------------------------------
# Show missing targets
# ------------------------------------------------------------

if missing_target.any():

    print("\nMissing target observations:")

    display(
        model_df.loc[
            missing_target,
            [
                "scheme_name",
                "month_date",
                "target_month",
                "expected_target_month"
            ]
        ]
    )


# ------------------------------------------------------------
# Show genuinely incorrect timing
# ------------------------------------------------------------

if timing_wrong.any():

    print("\nWARNING: Target timing is incorrect:")

    display(
        model_df.loc[
            timing_wrong,
            [
                "scheme_name",
                "month_date",
                "target_month",
                "expected_target_month"
            ]
        ].head(20)
    )

else:

    print("\n✓ No incorrect target timing found.")


# ------------------------------------------------------------
# Remove temporary column
# ------------------------------------------------------------

model_df.drop(
    columns=["expected_target_month"],
    inplace=True
)

======================================================================
TARGET TIMING VALIDATION
======================================================================
Correct target timing : 3,969
Missing target        : 1
Wrong target timing   : 0

Missing target observations:

,scheme_name,month_date,target_month,expected_target_month
2695,Edelweiss Recently Listed IPO Fund Direct Plan...,2018-02-01,NaT,2018-03-01

✓ No incorrect target timing found.

In [50]:
# ============================================================
# FINAL DATA QUALITY CHECK
# ============================================================

print("\n" + "=" * 70)
print("FINAL MODEL DATA CHECK")
print("=" * 70)

print("Rows:", len(model_df))
print("Funds:", model_df["scheme_name"].nunique())
print("Months:", model_df["month_date"].nunique())

print("\nMonths:")
print(
    model_df["month_date"]
    .sort_values()
    .drop_duplicates()
    .dt.strftime("%Y-%m")
    .tolist()
)

print("\nTarget distribution:")
print(
    model_df["outperforms_benchmark"]
    .value_counts(dropna=False)
)

print("\nMissing target:")
print(
    model_df["outperforms_benchmark"]
    .isna()
    .sum()
)

======================================================================
FINAL MODEL DATA CHECK
======================================================================
Rows: 3970
Funds: 62
Months: 84

Months:
['2013-01', '2013-02', '2013-03', '2013-04', '2013-05', '2013-06', '2013-07', '2013-08', '2013-09', '2013-10', '2013-11', '2013-12', '2014-01', '2014-02', '2014-03', '2014-04', '2014-05', '2014-06', '2014-07', '2014-08', '2014-09', '2014-10', '2014-11', '2014-12', '2015-01', '2015-02', '2015-03', '2015-04', '2015-05', '2015-06', '2015-07', '2015-08', '2015-09', '2015-10', '2015-11', '2015-12', '2016-01', '2016-02', '2016-03', '2016-04', '2016-05', '2016-06', '2016-07', '2016-08', '2016-09', '2016-10', '2016-11', '2016-12', '2017-01', '2017-02', '2017-03', '2017-04', '2017-05', '2017-06', '2017-07', '2017-08', '2017-09', '2017-10', '2017-11', '2017-12', '2018-01', '2018-02', '2018-03', '2018-04', '2018-05', '2018-06', '2018-07', '2018-08', '2018-09', '2018-10', '2018-11', '2018-12', '2019-01', '2019-02', '2019-03', '2019-04', '2019-05', '2019-06', '2019-07', '2019-08', '2019-09', '2019-10', '2019-11', '2019-12']

Target distribution:
outperforms_benchmark
1.0    2051
0.0    1918
NaN       1
Name: count, dtype: int64

Missing target:
1

In [51]:
# ============================================================
# ROLLING WINDOW CONFIGURATION
# ============================================================

MODEL_START_MONTH = pd.Timestamp("2013-01-01")
MODEL_END_MONTH   = pd.Timestamp("2019-12-01")

INITIAL_TRAIN_MONTHS = 60
OOS_MONTHS = 3
ROLL_MONTHS = 3

# ============================================================
# COVID PERIOD EXCLUSION
# ============================================================

EXCLUDE_COVID = False

COVID_START = pd.Timestamp("2020-01-01")
COVID_END   = pd.Timestamp("2021-12-01")

rolling_windows = []

train_start = MODEL_START_MONTH

window_id = 1

while True:

    train_end = (
        train_start
        + pd.DateOffset(months=INITIAL_TRAIN_MONTHS - 1)
    )

    oos_start = train_end + pd.DateOffset(months=1)

    oos_end = (
        oos_start
        + pd.DateOffset(months=OOS_MONTHS - 1)
    )

    if oos_end > MODEL_END_MONTH:
        break

    rolling_windows.append({
        "window": window_id,
        "train_start": train_start,
        "train_end": train_end,
        "oos_start": oos_start,
        "oos_end": oos_end
    })

    train_start = (
        train_start
        + pd.DateOffset(months=ROLL_MONTHS)
    )

    window_id += 1


rolling_windows_df = pd.DataFrame(
    rolling_windows
)

print(
    "Number of rolling windows:",
    len(rolling_windows_df)
)

display(rolling_windows_df)

Number of rolling windows: 8

   window train_start  train_end  oos_start    oos_end
0       1  2013-01-01 2017-12-01 2018-01-01 2018-03-01
1       2  2013-04-01 2018-03-01 2018-04-01 2018-06-01
2       3  2013-07-01 2018-06-01 2018-07-01 2018-09-01
3       4  2013-10-01 2018-09-01 2018-10-01 2018-12-01
4       5  2014-01-01 2018-12-01 2019-01-01 2019-03-01
5       6  2014-04-01 2019-03-01 2019-04-01 2019-06-01
6       7  2014-07-01 2019-06-01 2019-07-01 2019-09-01
7       8  2014-10-01 2019-09-01 2019-10-01 2019-12-01

In [52]:
# ============================================================
# REMOVE EXCLUDED PERIOD FROM TRAINING DATA
# ============================================================

def exclude_covid_period(df):

    if not EXCLUDE_COVID:
        return df.copy()

    mask = ~(
        (df["month_date"] >= COVID_START) &
        (df["month_date"] <= COVID_END)
    )

    return df.loc[mask].copy()

In [53]:
# ============================================================
# RANDOM FOREST HYPERPARAMETER GRID
# ============================================================

rf_param_grid = {
    "model__n_estimators": [
        200,
        500
    ],

    "model__max_depth": [
        None,
        5,
        10
    ],

    "model__min_samples_leaf": [
        5,
        10,
        20
    ]
}

print("RF parameter combinations:")

n_combinations = 1

for values in rf_param_grid.values():
    n_combinations *= len(values)

print(n_combinations)

RF parameter combinations:
18

In [54]:
# ============================================================
# CROSS-SECTIONAL CV SPLITS
# ============================================================

def make_cross_sectional_splits(
    df,
    n_splits=5
):
    """
    Create cross-sectional validation splits.

    Each fold uses entire months as validation periods,
    preventing observations from the same month from being
    split between training and validation.
    """

    months = (
        pd.Series(
            df["month_date"]
            .dropna()
            .unique()
        )
        .sort_values()
        .reset_index(drop=True)
    )

    month_folds = np.array_split(
        months,
        n_splits
    )

    splits = []

    for fold_months in month_folds:

        if len(fold_months) == 0:
            continue

        validation_mask = (
            df["month_date"]
            .isin(fold_months)
        )

        train_idx = np.where(
            ~validation_mask
        )[0]

        validation_idx = np.where(
            validation_mask
        )[0]

        splits.append(
            (
                train_idx,
                validation_idx
            )
        )

    return splits

In [55]:
print("model_df shape:", model_df.shape)
print("model_df date range:",
      model_df["month_date"].min(),
      model_df["month_date"].max())

print("\nRows by year:")
print(
    model_df.groupby(model_df["month_date"].dt.year)
            .size()
            .to_string()
)

print("\nTarget distribution:")
print(model_df[TARGET].value_counts(dropna=False))

print("\nSelected feature null counts:")
print(model_df[rf_features].isna().sum().sort_values(ascending=False))

model_df shape: (3970, 52)
model_df date range: 2013-01-01 00:00:00 2019-12-01 00:00:00

Rows by year:
month_date
2013    464
2014    480
2015    520
2016    569
2017    598
2018    636
2019    703

Target distribution:
outperforms_benchmark
1.0    2051
0.0    1918
NaN       1
Name: count, dtype: int64

Selected feature null counts:
t_hml_750      1951
ir_p3y         1951
t_umd_750      1951
r2_750         1951
t_smb_750      1951
sr_p3y         1951
const_250       708
sr_p1y          708
ir_p1y          708
t_hml_250       708
t_const_250     708
t_hml_180       498
const_180       498
t_const_180     498
ir_p6m          365
sr_p6m          365
t_const_120     330
t_hml_120       330
const_120       330
t_hml_90        254
t_const_90      254
const_90        254
dtype: int64

In [56]:
TRAIN_START = pd.Timestamp("2013-01-01")
TRAIN_END   = pd.Timestamp("2017-12-01")

train_raw = model_df[
    (model_df["month_date"] >= TRAIN_START) &
    (model_df["month_date"] <= TRAIN_END)
].copy()

print("\nTRAIN RAW:", train_raw.shape)

print("\nTrain rows by year:")
print(
    train_raw.groupby(train_raw["month_date"].dt.year)
             .size()
             .to_string()
)

print("\nTrain target:")
print(train_raw[TARGET].value_counts(dropna=False))

print("\nTrain null counts:")
print(
    train_raw[rf_features]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

TRAIN RAW: (2631, 52)

Train rows by year:
month_date
2013    464
2014    480
2015    520
2016    569
2017    598

Train target:
outperforms_benchmark
1.0    1339
0.0    1292
Name: count, dtype: int64

Train null counts:
t_hml_750      1697
ir_p3y         1697
t_umd_750      1697
r2_750         1697
t_smb_750      1697
sr_p3y         1697
const_250       601
sr_p1y          601
ir_p1y          601
t_hml_250       601
t_const_250     601
t_hml_180       413
const_180       413
t_const_180     413
ir_p6m          303
sr_p6m          303
t_const_120     269
t_hml_120       269
const_120       269
t_hml_90        208
t_const_90      208
const_90        208
dtype: int64

In [57]:
train = train_raw.dropna(
    subset=rf_features + [TARGET]
).copy()

print("\nTRAIN AFTER DROPNA:", train.shape)
print("Number of funds:", train["scheme_name"].nunique())

if len(train) > 0:
    print("\nTarget distribution after DROPNA:")
    print(train[TARGET].value_counts())

TRAIN AFTER DROPNA: (934, 52)
Number of funds: 41

Target distribution after DROPNA:
outperforms_benchmark
0.0    517
1.0    417
Name: count, dtype: int64

In [58]:
from sklearn.model_selection import KFold
# ============================================================
# RANDOM FOREST + IQR — ROLLING CV + OOS
# ============================================================

rf_iqr_oos_predictions = []
rf_iqr_cv_results = []

for _, w in rolling_windows_df.iterrows():

    window_id = int(w["window"])

    print("\n")
    print("=" * 70)
    print(f"WINDOW {window_id}")
    print("=" * 70)
    print(f"TRAIN: {w['train_start']:%Y-%m} → {w['train_end']:%Y-%m}")
    print(f"OOS:   {w['oos_start']:%Y-%m} → {w['oos_end']:%Y-%m}")

    # --------------------------------------------------------
    # TRAINING DATA
    # --------------------------------------------------------
    train = model_df[
        (model_df["month_date"] >= w["train_start"]) &
        (model_df["month_date"] <= w["train_end"])
    ].copy()

    train = exclude_covid_period(train)
    train = train.dropna(subset=rf_features + [TARGET]).copy()

    X_train = train[rf_features]
    y_train = train[TARGET].astype(int)

    # --------------------------------------------------------
    # OOS DATA
    # --------------------------------------------------------
    oos = model_df[
        (model_df["month_date"] >= w["oos_start"]) &
        (model_df["month_date"] <= w["oos_end"])
    ].copy()

    # OOS data is never used to learn IQR bounds.
    oos_predict = oos.dropna(subset=rf_features).copy()
    X_oos = oos_predict[rf_features]

    print(f"Training observations: {len(train):,}")
    print(f"OOS observations:      {len(oos_predict):,}")

    # --------------------------------------------------------
    # 5-FOLD K-FOLD CROSS-VALIDATION
    # --------------------------------------------------------
    cv = KFold(
        n_splits=5,
        shuffle=True,
        random_state=RANDOM_STATE
    )

    # --------------------------------------------------------
    # RF + IQR PIPELINE
    # --------------------------------------------------------
    # The anomaly transformer is inside the pipeline. Therefore,
    # each GridSearchCV training fold learns its own IQR bounds
    # using only that fold's training observations.
    rf_iqr_pipeline = Pipeline([
        ("anomaly", IQRAnomalyClipper(multiplier=IQR_MULTIPLIER)),
        ("scaler", StandardScaler()),
        ("model", RandomForestClassifier(
            random_state=RANDOM_STATE,
            n_jobs=-1,
            class_weight="balanced"
        ))
    ])

    # --------------------------------------------------------
    # GRID SEARCH
    # --------------------------------------------------------
    grid_search = GridSearchCV(
        estimator=rf_iqr_pipeline,
        param_grid=rf_param_grid,
        scoring="roc_auc",
        cv=cv,
        n_jobs=-1,
        refit=True
    )

    grid_search.fit(X_train, y_train)

    best_params = grid_search.best_params_
    best_cv_auc = grid_search.best_score_

    print("\nBest parameters:")
    print(best_params)
    print(f"Best CV ROC-AUC: {best_cv_auc:.4f}")

    # --------------------------------------------------------
    # OOS PREDICTION
    # --------------------------------------------------------
    oos_predict["rf_probability"] = grid_search.predict_proba(X_oos)[:, 1]
    oos_predict["rf_prediction"] = grid_search.predict(X_oos)

    # --------------------------------------------------------
    # WINDOW METADATA
    # --------------------------------------------------------
    oos_predict["rf_window"] = window_id
    oos_predict["rf_train_start"] = w["train_start"]
    oos_predict["rf_train_end"] = w["train_end"]
    oos_predict["rf_oos_start"] = w["oos_start"]
    oos_predict["rf_oos_end"] = w["oos_end"]
    oos_predict["rf_anomaly_method"] = "IQR_1.5"

    rf_iqr_oos_predictions.append(oos_predict)

    rf_iqr_cv_results.append({
        "window": window_id,
        "train_start": w["train_start"],
        "train_end": w["train_end"],
        "oos_start": w["oos_start"],
        "oos_end": w["oos_end"],
        "n_train": len(train),
        "n_oos": len(oos_predict),
        "best_cv_auc": best_cv_auc,
        "best_n_estimators": best_params["model__n_estimators"],
        "best_max_depth": best_params["model__max_depth"],
        "best_min_samples_leaf": best_params["model__min_samples_leaf"],
        "anomaly_method": "IQR_1.5"
    })

    print(f"Mean P(outperformance): {oos_predict['rf_probability'].mean():.4f}")

# ============================================================
# COMBINE ALL OOS PREDICTIONS
# ============================================================
rf_iqr_oos_df = pd.concat(rf_iqr_oos_predictions, ignore_index=True)
rf_iqr_cv_results_df = pd.DataFrame(rf_iqr_cv_results)

print("\n")
print("=" * 70)
print("RF + IQR OOS PREDICTION COMPLETE")
print("=" * 70)
print("Total OOS predictions:", len(rf_iqr_oos_df))
print("Unique funds:", rf_iqr_oos_df["scheme_name"].nunique())
print("OOS months:", rf_iqr_oos_df["month_date"].nunique())
display(rf_iqr_cv_results_df)

======================================================================
WINDOW 1
======================================================================
TRAIN: 2013-01 → 2017-12
OOS:   2018-01 → 2018-03
Training observations: 934
OOS observations:      126

D:\PycharmProjects\mf-ml\.venv\Lib\site-packages\joblib\externals\loky\backend\resource_tracker.py:146: UserWarning: resource_tracker: process died unexpectedly, relaunching. Some folders/semaphores might leak.
  warnings.warn(

Best parameters:
{'model__max_depth': None, 'model__min_samples_leaf': 10, 'model__n_estimators': 500}
Best CV ROC-AUC: 0.5958
Mean P(outperformance): 0.4409


======================================================================
WINDOW 2
======================================================================
TRAIN: 2013-04 → 2018-03
OOS:   2018-04 → 2018-06
Training observations: 1,060
OOS observations:      129

Best parameters:
{'model__max_depth': 10, 'model__min_samples_leaf': 10, 'model__n_estimators': 500}
Best CV ROC-AUC: 0.6156
Mean P(outperformance): 0.4167


======================================================================
WINDOW 3
======================================================================
TRAIN: 2013-07 → 2018-06
OOS:   2018-07 → 2018-09
Training observations: 1,189
OOS observations:      130

Best parameters:
{'model__max_depth': None, 'model__min_samples_leaf': 5, 'model__n_estimators': 500}
Best CV ROC-AUC: 0.6034
Mean P(outperformance): 0.4413


======================================================================
WINDOW 4
======================================================================
TRAIN: 2013-10 → 2018-09
OOS:   2018-10 → 2018-12
Training observations: 1,319
OOS observations:      133

Best parameters:
{'model__max_depth': 10, 'model__min_samples_leaf': 5, 'model__n_estimators': 500}
Best CV ROC-AUC: 0.6089
Mean P(outperformance): 0.4703


======================================================================
WINDOW 5
======================================================================
TRAIN: 2014-01 → 2018-12
OOS:   2019-01 → 2019-03
Training observations: 1,452
OOS observations:      141

Best parameters:
{'model__max_depth': None, 'model__min_samples_leaf': 5, 'model__n_estimators': 200}
Best CV ROC-AUC: 0.6032
Mean P(outperformance): 0.4943


======================================================================
WINDOW 6
======================================================================
TRAIN: 2014-04 → 2019-03
OOS:   2019-04 → 2019-06
Training observations: 1,593
OOS observations:      141

Best parameters:
{'model__max_depth': None, 'model__min_samples_leaf': 5, 'model__n_estimators': 500}
Best CV ROC-AUC: 0.6094
Mean P(outperformance): 0.5477


======================================================================
WINDOW 7
======================================================================
TRAIN: 2014-07 → 2019-06
OOS:   2019-07 → 2019-09
Training observations: 1,734
OOS observations:      141

Best parameters:
{'model__max_depth': None, 'model__min_samples_leaf': 10, 'model__n_estimators': 200}
Best CV ROC-AUC: 0.6061
Mean P(outperformance): 0.5439


======================================================================
WINDOW 8
======================================================================
TRAIN: 2014-10 → 2019-09
OOS:   2019-10 → 2019-12
Training observations: 1,875
OOS observations:      144

Best parameters:
{'model__max_depth': 10, 'model__min_samples_leaf': 5, 'model__n_estimators': 500}
Best CV ROC-AUC: 0.6214
Mean P(outperformance): 0.6024


======================================================================
RF + IQR OOS PREDICTION COMPLETE
======================================================================
Total OOS predictions: 1085
Unique funds: 49
OOS months: 24

,window,train_start,train_end,oos_start,oos_end,n_train,n_oos,best_cv_auc,best_n_estimators,best_max_depth,best_min_samples_leaf,anomaly_method
0,1,2013-01-01,2017-12-01,2018-01-01,2018-03-01,934,126,0.595774,500,NaN,10,IQR_1.5
1,2,2013-04-01,2018-03-01,2018-04-01,2018-06-01,1060,129,0.615613,500,10.0,10,IQR_1.5
2,3,2013-07-01,2018-06-01,2018-07-01,2018-09-01,1189,130,0.603430,500,NaN,5,IQR_1.5
3,4,2013-10-01,2018-09-01,2018-10-01,2018-12-01,1319,133,0.608860,500,10.0,5,IQR_1.5
4,5,2014-01-01,2018-12-01,2019-01-01,2019-03-01,1452,141,0.603173,200,NaN,5,IQR_1.5
5,6,2014-04-01,2019-03-01,2019-04-01,2019-06-01,1593,141,0.609387,500,NaN,5,IQR_1.5
6,7,2014-07-01,2019-06-01,2019-07-01,2019-09-01,1734,141,0.606141,200,NaN,10,IQR_1.5
7,8,2014-10-01,2019-09-01,2019-10-01,2019-12-01,1875,144,0.621438,500,10.0,5,IQR_1.5

In [59]:
# ============================================================
# CHECK RF + IQR OOS PREDICTIONS
# ============================================================

print("RF + IQR OOS shape:", rf_iqr_oos_df.shape)

display(
    rf_iqr_oos_df[
        [
            "scheme_name",
            "month_date",
            "target_month",
            "rf_probability",
            "rf_prediction",
            "rf_window",
            "rf_anomaly_method"
        ]
    ].head(20)
)

RF + IQR OOS shape: (1085, 60)

,scheme_name,month_date,target_month,rf_probability,rf_prediction,rf_window,rf_anomaly_method
0,Aditya Birla Sun Life ELSS Tax Saver Fund - Gr...,2018-01-01,2018-02-01,0.415276,0,1,IQR_1.5
1,Aditya Birla Sun Life Flexi Cap Fund - Growth ...,2018-01-01,2018-02-01,0.455627,0,1,IQR_1.5
2,Aditya Birla Sun Life Focused Fund - Growth - ...,2018-01-01,2018-02-01,0.399758,0,1,IQR_1.5
3,Aditya Birla Sun Life Value Fund - Growth - Di...,2018-01-01,2018-02-01,0.352560,0,1,IQR_1.5
4,Axis ELSS Tax Saver Fund - Direct Plan - Growt...,2018-01-01,2018-02-01,0.292891,0,1,IQR_1.5
5,Axis Focused Fund - Direct Plan - Growth Option,2018-01-01,2018-02-01,0.321520,0,1,IQR_1.5
6,DSP ELSS Tax Saver Fund - Direct Plan - Growth,2018-01-01,2018-02-01,0.506582,1,1,IQR_1.5
7,DSP Flexi Cap Fund - Direct Plan - Growth,2018-01-01,2018-02-01,0.463681,0,1,IQR_1.5
8,DSP Focused Fund - Direct Plan - Growth,2018-01-01,2018-02-01,0.506920,1,1,IQR_1.5
9,DSP Large & Mid Cap Fund - Direct Plan - Growth,2018-01-01,2018-02-01,0.493267,0,1,IQR_1.5
10,Edelweiss ELSS Tax Saver Fund - Direct Plan-Gr...,2018-01-01,2018-02-01,0.285959,0,1,IQR_1.5
11,Franklin India ELSS Tax Saver Fund - Direct - ...,2018-01-01,2018-02-01,0.272097,0,1,IQR_1.5
12,Franklin India Flexi Cap Fund - Direct - Growth,2018-01-01,2018-02-01,0.279080,0,1,IQR_1.5
13,Franklin India Focused Equity Fund - Direct - ...,2018-01-01,2018-02-01,0.357424,0,1,IQR_1.5
14,Franklin India Large & Mid Cap Fund - Direct -...,2018-01-01,2018-02-01,0.277609,0,1,IQR_1.5
15,Franklin India Opportunities Fund - Direct - G...,2018-01-01,2018-02-01,0.271961,0,1,IQR_1.5
16,HDFC ELSS Tax saver - Growth Option - Direct Plan,2018-01-01,2018-02-01,0.392478,0,1,IQR_1.5
17,HDFC Flexi Cap Fund - Growth Option - Direct Plan,2018-01-01,2018-02-01,0.389273,0,1,IQR_1.5
18,HDFC Focused Fund - Growth Option - Direct Plan,2018-01-01,2018-02-01,0.411575,0,1,IQR_1.5
19,HDFC Infrastructure Fund - Growth Option - Dir...,2018-01-01,2018-02-01,0.562772,1,1,IQR_1.5

In [60]:
# ============================================================
# PREPARE RF + IQR PREDICTIONS FOR DATABASE
# ============================================================

rf_iqr_db = rf_iqr_oos_df[
    [
        "scheme_name",
        "month_date",
        "target_month",
        "rf_probability",
        "rf_prediction",
        "rf_window",
        "rf_train_start",
        "rf_train_end",
        "rf_oos_start",
        "rf_oos_end",
        "rf_anomaly_method"
    ]
].copy()

print("Rows to save:", len(rf_iqr_db))

Rows to save: 1085

In [ ]:
# # ============================================================
# # DATABASE CONNECTION
# # ============================================================
#
# from sqlalchemy import create_engine
# import os
#
# # Prefer MF_DB_URL as an environment variable. If it is not set,
# # the local connection below keeps this notebook compatible with
# # the existing setup.
# db_url = os.getenv("MF_DB_URL")
#
# if db_url:
#     engine = create_engine(db_url)
# else:
#     engine = create_engine(
#         "postgresql+psycopg2://postgres:Password%40123@localhost:5432/mfdb"
#     )
#
# print(type(engine))
# print("Database engine created.")

In [61]:
# ============================================================
# SAVE RF + IQR OOS PREDICTIONS TO NEW TABLES
# ============================================================

from datetime import datetime

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

prediction_table_name = f"pre_covid_oos_predictions_rf_iqr_{RUN_TIMESTAMP}"
cv_table_name = f"pre_covid_rf_iqr_cv_results_{RUN_TIMESTAMP}"

print("Saving RF + IQR predictions to:")
print(f"mf200.{prediction_table_name}")
print("Saving CV results to:")
print(f"mf200.{cv_table_name}")

# ------------------------------------------------------------
# SAVE OOS PREDICTIONS
# ------------------------------------------------------------
rf_iqr_db.to_sql(
    name=prediction_table_name,
    con=engine,
    schema="mf200",
    if_exists="fail",
    index=False
)

# ------------------------------------------------------------
# SAVE CV RESULTS
# ------------------------------------------------------------
rf_iqr_cv_results_df.to_sql(
    name=cv_table_name,
    con=engine,
    schema="mf200",
    if_exists="fail",
    index=False
)

print()
print("=" * 70)
print("RF + IQR RESULTS SAVED")
print("=" * 70)
print(f"Prediction table: mf200.{prediction_table_name}")
print(f"Rows             : {len(rf_iqr_db):,}")
print(f"Funds            : {rf_iqr_db['scheme_name'].nunique():,}")
print(f"Months           : {rf_iqr_db['month_date'].nunique():,}")
print(f"CV table         : mf200.{cv_table_name}")
print("CV rows          :", len(rf_iqr_cv_results_df))

Saving RF + IQR predictions to:
mf200.pre_covid_oos_predictions_rf_iqr_20260912_003517
Saving CV results to:
mf200.pre_covid_rf_iqr_cv_results_20260912_003517

======================================================================
RF + IQR RESULTS SAVED
======================================================================
Prediction table: mf200.pre_covid_oos_predictions_rf_iqr_20260912_003517
Rows             : 1,085
Funds            : 49
Months           : 24
CV table         : mf200.pre_covid_rf_iqr_cv_results_20260912_003517
CV rows          : 8

In [62]:
oos = model_df[
    (model_df["month_date"] >= w["oos_start"]) &
    (model_df["month_date"] <= w["oos_end"])
].copy()

oos_predict = oos.dropna(subset=rf_features).copy()

oos_predict["rf_probability"] = (
    grid_search.predict_proba(X_oos)[:, 1]
)

In [63]:
oos["scheme_name"].isin(train["scheme_name"])

3786     True
3787     True
3788     True
3789     True
3790     True
        ...
3965    False
3966    False
3967     True
3968     True
3969     True
Name: scheme_name, Length: 184, dtype: bool

In [64]:
training_funds = set(train["scheme_name"])
oos_funds = set(oos_predict["scheme_name"])

new_funds = oos_funds - training_funds

In [65]:
# ============================================================
# CHECK FOR NEW FUNDS IN OOS
# ============================================================

train_funds = set(train["scheme_name"].unique())

oos_fund_status = (
    oos_predict[["scheme_name", "month_date"]]
    .drop_duplicates()
    .copy()
)

oos_fund_status["seen_in_training"] = (
    oos_fund_status["scheme_name"].isin(train_funds)
)

new_funds_by_month = (
    oos_fund_status
    .groupby("month_date")
    .agg(
        total_oos_funds=("scheme_name", "nunique"),
        training_funds=("seen_in_training", "sum"),
        new_funds=("seen_in_training", lambda x: (~x).sum())
    )
    .reset_index()
)

print(new_funds_by_month)

  month_date  total_oos_funds  training_funds  new_funds
0 2019-10-01               47              47          0
1 2019-11-01               48              47          1
2 2019-12-01               49              47          2