In [1]:
# ============================================================
# IMPORTS + GLOBAL CONFIGURATION
# ============================================================

import os
import numpy as np
import pandas as pd

from datetime import datetime
from sqlalchemy import create_engine, text

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold, GridSearchCV

from xgboost import XGBClassifier

RANDOM_STATE = 42
TARGET = "outperforms_benchmark"

IQR_MULTIPLIER = 1.5

MODEL_START_MONTH = pd.Timestamp("2019-01-01")
MODEL_END_MONTH   = pd.Timestamp("2025-12-01")

INITIAL_TRAIN_MONTHS = 60
OOS_MONTHS = 3
ROLL_MONTHS = 3
N_CV_SPLITS = 5

EXCLUDE_COVID = True
COVID_START = pd.Timestamp("2020-01-01")
COVID_END   = pd.Timestamp("2021-12-01")

print("=" * 70)
print("XGBOOST + IQR CONFIGURATION")
print("=" * 70)
print(f"Model period       : {MODEL_START_MONTH:%Y-%m} → {MODEL_END_MONTH:%Y-%m}")
print(f"Training window    : {INITIAL_TRAIN_MONTHS} months")
print(f"OOS period         : {OOS_MONTHS} months")
print(f"Rolling step       : {ROLL_MONTHS} months")
print(f"CV folds           : {N_CV_SPLITS}")
print(f"COVID exclusion    : {EXCLUDE_COVID}")
print(f"IQR multiplier     : {IQR_MULTIPLIER}")

======================================================================
XGBOOST + IQR CONFIGURATION
======================================================================
Model period       : 2019-01 → 2025-12
Training window    : 60 months
OOS period         : 3 months
Rolling step       : 3 months
CV folds           : 5
COVID exclusion    : True
IQR multiplier     : 1.5

In [2]:
# ============================================================
# FINAL 22 IC-SELECTED FEATURES
# ============================================================

SELECTED_FEATURES_IC = [
    "t_hml_750",
    "t_hml_250",
    "t_hml_180",
    "ir_p1y",
    "sr_p1y",
    "ir_p3y",
    "t_hml_120",
    "t_const_250",
    "ir_p6m",
    "sr_p3y",
    "t_hml_90",
    "t_const_180",
    "sr_p6m",
    "const_250",
    "const_180",
    "const_90",
    "t_const_90",
    "t_umd_750",
    "const_120",
    "t_const_120",
    "t_smb_750",
    "r2_750",
]

selected_features = SELECTED_FEATURES_IC.copy()

print("Number of selected features:", len(selected_features))
for i, feature in enumerate(selected_features, 1):
    print(f"{i:2d}. {feature}")

Number of selected features: 22
 1. t_hml_750
 2. t_hml_250
 3. t_hml_180
 4. ir_p1y
 5. sr_p1y
 6. ir_p3y
 7. t_hml_120
 8. t_const_250
 9. ir_p6m
10. sr_p3y
11. t_hml_90
12. t_const_180
13. sr_p6m
14. const_250
15. const_180
16. const_90
17. t_const_90
18. t_umd_750
19. const_120
20. t_const_120
21. t_smb_750
22. r2_750

In [3]:
from pathlib import Path

RUN_TIMESTAMP_FILE = Path("D:\\PycharmProjects\\mf-ml\\run_timestamp.txt")

if not RUN_TIMESTAMP_FILE.exists():
    raise FileNotFoundError(
        f"Run timestamp file not found: {RUN_TIMESTAMP_FILE.resolve()}"
    )

RUN_TIMESTAMP = RUN_TIMESTAMP_FILE.read_text().strip()

if not RUN_TIMESTAMP:
    raise ValueError("run_timestamp.txt is empty")

print("Run timestamp:", RUN_TIMESTAMP)

Run timestamp: 20260905_003517

In [4]:
# ============================================================
# IQR ANOMALY CLIPPER
# ============================================================

class IQRAnomalyClipper(BaseEstimator, TransformerMixin):
    """Clip values outside Tukey IQR fences learned from fit data only."""

    def __init__(self, multiplier=1.5):
        self.multiplier = multiplier

    def fit(self, X, y=None):
        if isinstance(X, pd.DataFrame):
            X_df = X.copy()
        else:
            X_df = pd.DataFrame(X)

        self.feature_names_in_ = np.asarray(X_df.columns, dtype=object)
        self.n_features_in_ = X_df.shape[1]

        self.q1_ = X_df.quantile(0.25)
        self.q3_ = X_df.quantile(0.75)
        self.iqr_ = self.q3_ - self.q1_

        self.lower_bounds_ = self.q1_ - self.multiplier * self.iqr_
        self.upper_bounds_ = self.q3_ + self.multiplier * self.iqr_

        return self

    def transform(self, X):
        if isinstance(X, pd.DataFrame):
            X_df = X.copy()
            X_df.columns = self.feature_names_in_
        else:
            X_df = pd.DataFrame(X, columns=self.feature_names_in_)

        X_clipped = X_df.clip(
            lower=self.lower_bounds_,
            upper=self.upper_bounds_,
            axis="columns"
        )

        return X_clipped.to_numpy()

In [5]:
# # ============================================================
# # DATABASE CONNECTION
# # ============================================================
#
# # Prefer the environment-variable connection used by the project.
# # Supports both names used in the project.
#
# from sqlalchemy import create_engine
#
# engine = create_engine(
#     "postgresql+psycopg2://postgres:Password%40123@localhost:5432/mfdb"
# )
#
# print(type(engine))
#
# print("Database engine created.")

In [6]:
# ============================================================
# PREPARE MODEL DATA
# ============================================================

import os
import pandas as pd
from sqlalchemy import create_engine, text


# ------------------------------------------------------------
# DATABASE CONNECTION
# ------------------------------------------------------------
# ============================================================
# 1. DATABASE CONNECTION
# ============================================================

from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:Password%40123@localhost:5432/mfdb"
)

print(type(engine))

print("Database engine created.")

SOURCE_TABLE = f"feature_matrix_2019_2025_{RUN_TIMESTAMP}"

# ============================================================
# 1. LOAD FEATURE MATRIX
# ============================================================

FEATURE_SQL = f"""
SELECT *
FROM mf200.{SOURCE_TABLE}
ORDER BY month_date, scheme_name
"""

features_df = pd.read_sql(
    text(FEATURE_SQL),
    engine
)

features_df["month_date"] = pd.to_datetime(
    features_df["month_date"],
    errors="coerce"
)

features_df["performance_date"] = pd.to_datetime(
    features_df["performance_date"],
    errors="coerce"
)


print("=" * 70)
print("FEATURE MATRIX")
print("=" * 70)

print("Shape:", features_df.shape)

print(
    "Date range:",
    features_df["month_date"].min(),
    "→",
    features_df["month_date"].max()
)

print(
    "Unique funds:",
    features_df["scheme_name"].nunique()
)

display(features_df.head())

<class 'sqlalchemy.engine.base.Engine'>
Database engine created.
======================================================================
FEATURE MATRIX
======================================================================
Shape: (6114, 46)
Date range: 2019-02-01 00:00:00 → 2025-12-01 00:00:00
Unique funds: 156

,scheme_name,month_date,performance_date,tna,vol_flows,const_90,const_120,const_180,const_250,const_750,...,t_umd_120,t_umd_180,t_umd_250,t_umd_750,ir_p6m,ir_p1y,ir_p3y,sr_p6m,sr_p1y,sr_p3y
0,Axis Flexi Cap Fund,2019-02-01,2019-02-28,3033.120265,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DSP ELSS Tax Saver Fund,2019-02-01,2019-02-28,4740.485947,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,DSP Flexi Cap Fund,2019-02-01,2019-02-28,2483.602286,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DSP Large & Mid Cap Fund,2019-02-01,2019-02-28,5416.097089,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Edelweiss ELSS Tax saver Fund,2019-02-01,2019-02-28,78.840000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# # ============================================================
# # LOAD FEATURE MATRIX
# # ============================================================
#
# FEATURE_SQL = """
# SELECT *
# FROM mf200.feature_matrix_2019_2025
# WHERE month_date >= DATE '2019-01-01'
#   AND month_date <= DATE '2025-12-01'
# ORDER BY month_date, scheme_name
# """
#
# features_df = pd.read_sql(text(FEATURE_SQL), engine)
#
# features_df["month_date"] = pd.to_datetime(
#     features_df["month_date"], errors="coerce"
# )
#
# if "performance_date" in features_df.columns:
#     features_df["performance_date"] = pd.to_datetime(
#         features_df["performance_date"], errors="coerce"
#     )
#
# print("=" * 70)
# print("FEATURE MATRIX")
# print("=" * 70)
# print("Shape:", features_df.shape)
# print("Date range:", features_df["month_date"].min(), "→", features_df["month_date"].max())
# print("Unique funds:", features_df["scheme_name"].nunique())

In [8]:
# ============================================================
# LOAD NIFTY 500 TRI FUND-MONTH UNIVERSE
# ============================================================
#
# Use the latest raw observation in each scheme/month.
# A fund-month is eligible only when that latest observation
# has benchmark = 'Nifty 500 TRI'.
# ============================================================

NIFTY500_UNIVERSE_SQL = """
WITH monthly_benchmark AS (
    SELECT
        "schemeName" AS scheme_name,
        DATE_TRUNC('month', report_date)::date AS month_date,
        benchmark,
        ROW_NUMBER() OVER (
            PARTITION BY
                "schemeName",
                DATE_TRUNC('month', report_date)
            ORDER BY report_date DESC
        ) AS rn
    FROM mf200.crisil_fund_daily_raw
    WHERE
        "schemeName" IS NOT NULL
        AND report_date IS NOT NULL
)
SELECT
    scheme_name,
    month_date
FROM monthly_benchmark
WHERE
    rn = 1
    AND benchmark = 'Nifty 500 TRI'
    AND month_date >= DATE '2019-01-01'
    AND month_date <= DATE '2025-12-01'
ORDER BY month_date, scheme_name
"""

nifty500_fund_months = pd.read_sql(
    text(NIFTY500_UNIVERSE_SQL),
    engine
)

nifty500_fund_months["month_date"] = pd.to_datetime(
    nifty500_fund_months["month_date"], errors="coerce"
)

print("=" * 70)
print("NIFTY 500 TRI FUND-MONTH UNIVERSE")
print("=" * 70)
print("Fund-month observations:", len(nifty500_fund_months))
print("Unique funds:", nifty500_fund_months["scheme_name"].nunique())
print("Unique months:", nifty500_fund_months["month_date"].nunique())

display(nifty500_fund_months.head())

======================================================================
NIFTY 500 TRI FUND-MONTH UNIVERSE
======================================================================
Fund-month observations: 6161
Unique funds: 156
Unique months: 84

                     scheme_name month_date
0            Axis Flexi Cap Fund 2019-01-01
1        DSP ELSS Tax Saver Fund 2019-01-01
2             DSP Flexi Cap Fund 2019-01-01
3       DSP Large & Mid Cap Fund 2019-01-01
4  Edelweiss ELSS Tax saver Fund 2019-01-01

In [9]:
# ============================================================
# LOAD TARGET DATA
# ============================================================

TARGET_SQL = """
SELECT
    scheme_name,
    month_date,
    target_month,
    outperforms_benchmark,
    excess_return_percent,
    current_monthly_return_percent,
    current_benchmark_monthly_return_percent
FROM mf200.fund_monthly_outperformance_targets
ORDER BY scheme_name, month_date
"""

target_df = pd.read_sql(text(TARGET_SQL), engine)

target_df["month_date"] = pd.to_datetime(
    target_df["month_date"], errors="coerce"
)
target_df["target_month"] = pd.to_datetime(
    target_df["target_month"], errors="coerce"
)

print("=" * 70)
print("TARGET DATA")
print("=" * 70)
print("Shape:", target_df.shape)
print("Date range:", target_df["month_date"].min(), "→", target_df["month_date"].max())
print("Target distribution:")
print(target_df[TARGET].value_counts(dropna=False))

======================================================================
TARGET DATA
======================================================================
Shape: (7067, 7)
Date range: 2019-01-01 00:00:00 → 2026-06-01 00:00:00
Target distribution:
outperforms_benchmark
1    3620
0    3447
Name: count, dtype: int64

In [10]:
# ============================================================
# JOIN FEATURES + TARGET + NIFTY 500 TRI UNIVERSE
# ============================================================

model_df = features_df.merge(
    target_df[
        [
            "scheme_name",
            "month_date",
            "target_month",
            TARGET,
            "excess_return_percent",
            "current_monthly_return_percent",
            "current_benchmark_monthly_return_percent",
        ]
    ],
    on=["scheme_name", "month_date"],
    how="left"
)

model_df = model_df.merge(
    nifty500_fund_months,
    on=["scheme_name", "month_date"],
    how="inner"
)

model_df = model_df.sort_values(
    ["month_date", "scheme_name"]
).reset_index(drop=True)

print("=" * 70)
print("MODEL DATA")
print("=" * 70)
print("Shape:", model_df.shape)
print("Feature month:", model_df["month_date"].min(), "→", model_df["month_date"].max())
print("Unique funds:", model_df["scheme_name"].nunique())
print("Unique months:", model_df["month_date"].nunique())

======================================================================
MODEL DATA
======================================================================
Shape: (6106, 51)
Feature month: 2019-02-01 00:00:00 → 2025-12-01 00:00:00
Unique funds: 155
Unique months: 83

In [11]:
# ============================================================
# TARGET TIMING VALIDATION
# ============================================================

model_df["expected_target_month"] = (
    model_df["month_date"] + pd.DateOffset(months=1)
)

missing_target = model_df[TARGET].isna()
target_exists = ~missing_target

timing_ok = (
    target_exists
    & (model_df["target_month"] == model_df["expected_target_month"])
)

timing_wrong = (
    target_exists
    & (model_df["target_month"] != model_df["expected_target_month"])
)

print("=" * 70)
print("TARGET TIMING VALIDATION")
print("=" * 70)
print(f"Correct target timing : {timing_ok.sum():,}")
print(f"Missing target        : {missing_target.sum():,}")
print(f"Wrong target timing   : {timing_wrong.sum():,}")

if missing_target.any():
    print("Missing target observations:")
    display(
        model_df.loc[
            missing_target,
            ["scheme_name", "month_date", "target_month", "expected_target_month"]
        ]
    )

if timing_wrong.any():
    print("WARNING: Incorrect target timing:")
    display(
        model_df.loc[
            timing_wrong,
            ["scheme_name", "month_date", "target_month", "expected_target_month"]
        ].head(20)
    )
else:
    print("✓ No incorrect target timing found.")

model_df.drop(columns=["expected_target_month"], inplace=True)

======================================================================
TARGET TIMING VALIDATION
======================================================================
Correct target timing : 6,103
Missing target        : 3
Wrong target timing   : 0
Missing target observations:

,scheme_name,month_date,target_month,expected_target_month
307,Quant Multi Cap Fund,2019-12-01,NaT,2020-01-01
772,Mahindra Manulife Multi Cap Fund,2021-01-01,NaT,2021-02-01
4799,Navi ELSS Tax Saver Fund,2025-03-01,NaT,2025-04-01

✓ No incorrect target timing found.

In [12]:
# ============================================================
# FINAL DATA QUALITY CHECK
# ============================================================

print("=" * 70)
print("FINAL MODEL DATA CHECK")
print("=" * 70)
print("Rows:", len(model_df))
print("Funds:", model_df["scheme_name"].nunique())
print("Months:", model_df["month_date"].nunique())

feature_missing = (
    model_df[selected_features]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

feature_availability = pd.DataFrame({
    "missing_rows": feature_missing,
    "missing_percent": feature_missing / len(model_df) * 100
})

display(feature_availability)

print("Target distribution:")
print(model_df[TARGET].value_counts(dropna=False))

======================================================================
FINAL MODEL DATA CHECK
======================================================================
Rows: 6106
Funds: 155
Months: 83

             missing_rows  missing_percent
t_hml_750            4114        67.376351
ir_p3y               4114        67.376351
t_umd_750            4114        67.376351
r2_750               4114        67.376351
t_smb_750            4114        67.376351
sr_p3y               4114        67.376351
const_250            1689        27.661317
sr_p1y               1689        27.661317
ir_p1y               1689        27.661317
t_hml_250            1689        27.661317
t_const_250          1689        27.661317
t_hml_180            1224        20.045857
const_180            1224        20.045857
t_const_180          1224        20.045857
ir_p6m                861        14.100884
sr_p6m                861        14.100884
t_const_120           790        12.938094
t_hml_120             790        12.938094
const_120             790        12.938094
t_hml_90              613        10.039306
t_const_90            613        10.039306
const_90              613        10.039306

Target distribution:
outperforms_benchmark
1.0    3127
0.0    2976
NaN       3
Name: count, dtype: int64

In [13]:
# ============================================================
# ROLLING WINDOW CONFIGURATION
# ============================================================

rolling_windows = []

train_start = MODEL_START_MONTH
window_id = 1

while True:
    train_end = (
        train_start
        + pd.DateOffset(months=INITIAL_TRAIN_MONTHS - 1)
    )

    oos_start = train_end + pd.DateOffset(months=1)

    oos_end = (
        oos_start
        + pd.DateOffset(months=OOS_MONTHS - 1)
    )

    if oos_end > MODEL_END_MONTH:
        break

    rolling_windows.append({
        "window": window_id,
        "train_start": train_start,
        "train_end": train_end,
        "oos_start": oos_start,
        "oos_end": oos_end
    })

    train_start = (
        train_start
        + pd.DateOffset(months=ROLL_MONTHS)
    )
    window_id += 1

rolling_windows_df = pd.DataFrame(rolling_windows)

print("=" * 70)
print("ROLLING WINDOWS")
print("=" * 70)
print("Number of rolling windows:", len(rolling_windows_df))
display(rolling_windows_df)

======================================================================
ROLLING WINDOWS
======================================================================
Number of rolling windows: 8

   window train_start  train_end  oos_start    oos_end
0       1  2019-01-01 2023-12-01 2024-01-01 2024-03-01
1       2  2019-04-01 2024-03-01 2024-04-01 2024-06-01
2       3  2019-07-01 2024-06-01 2024-07-01 2024-09-01
3       4  2019-10-01 2024-09-01 2024-10-01 2024-12-01
4       5  2020-01-01 2024-12-01 2025-01-01 2025-03-01
5       6  2020-04-01 2025-03-01 2025-04-01 2025-06-01
6       7  2020-07-01 2025-06-01 2025-07-01 2025-09-01
7       8  2020-10-01 2025-09-01 2025-10-01 2025-12-01

In [14]:
# ============================================================
# COVID PERIOD EXCLUSION
# ============================================================

def exclude_covid_period(df):
    if not EXCLUDE_COVID:
        return df.copy()

    mask = ~(
        (df["month_date"] >= COVID_START)
        & (df["month_date"] <= COVID_END)
    )

    return df.loc[mask].copy()

In [15]:
# ============================================================
# LIGHTGBM HYPERPARAMETER GRID
# ============================================================

from lightgbm import LGBMClassifier

lgbm_param_grid = {

    "model__n_estimators": [200, 500],

    "model__learning_rate": [0.05, 0.10],

    "model__num_leaves": [31, 63],

    "model__max_depth": [5, 8],

    "model__subsample": [0.8, 1.0],

    "model__colsample_bytree": [0.8, 1.0]

}

print("="*70)
print("LIGHTGBM HYPERPARAMETER GRID")
print("="*70)

n_combinations = np.prod([len(v) for v in lgbm_param_grid.values()])

print("Parameter combinations:", n_combinations)

======================================================================
LIGHTGBM HYPERPARAMETER GRID
======================================================================
Parameter combinations: 64

In [16]:
# ============================================================
# LIGHTGBM + IQR ROLLING OOS PREDICTION
# ============================================================

lgbm_iqr_oos_predictions = []
lgbm_iqr_cv_results = []

print("="*70)
print("STARTING ROLLING LIGHTGBM + IQR OOS PREDICTION")
print("="*70)

for _, w in rolling_windows_df.iterrows():

    window_id = int(w["window"])

    print("\n" + "="*70)
    print(f"WINDOW {window_id}")
    print("="*70)

    print(f"TRAIN : {w['train_start']:%Y-%m} → {w['train_end']:%Y-%m}")
    print(f"OOS   : {w['oos_start']:%Y-%m} → {w['oos_end']:%Y-%m}")

    train = model_df[
        (model_df.month_date >= w.train_start) &
        (model_df.month_date <= w.train_end)
    ].copy()

    train = exclude_covid_period(train)

    train = train.dropna(
        subset=selected_features + [TARGET]
    )

    X_train = train[selected_features]
    y_train = train[TARGET].astype(int)

    oos = model_df[
        (model_df.month_date >= w.oos_start) &
        (model_df.month_date <= w.oos_end)
    ].copy()

    oos_predict = oos.dropna(subset=selected_features)

    X_oos = oos_predict[selected_features]

    print("Training observations:", len(X_train))
    print("OOS observations     :", len(X_oos))

    cv = KFold(
        n_splits=5,
        shuffle=True,
        random_state=RANDOM_STATE
    )

    lgbm_pipeline = Pipeline([

        ("anomaly", IQRAnomalyClipper(multiplier=1.5)),

        ("scaler", StandardScaler()),

        ("model",
            LGBMClassifier(
                objective="binary",
                random_state=RANDOM_STATE,
                n_jobs=-1,
                verbosity=-1
            )
        )
    ])

    lgbm_grid = GridSearchCV(

        estimator=lgbm_pipeline,

        param_grid=lgbm_param_grid,

        scoring="roc_auc",

        cv=cv,

        n_jobs=-1,

        refit=True,

        return_train_score=False

    )

    lgbm_grid.fit(X_train, y_train)

    print("\nBest parameters")
    print(lgbm_grid.best_params_)
    print("Best CV ROC-AUC:", round(lgbm_grid.best_score_,4))

    oos_predict["lgbm_probability"] = (
        lgbm_grid.predict_proba(X_oos)[:,1]
    )

    oos_predict["lgbm_prediction"] = (
        lgbm_grid.predict(X_oos)
    )

    oos_predict["lgbm_window"] = window_id

    oos_predict["lgbm_train_start"] = w.train_start
    oos_predict["lgbm_train_end"] = w.train_end

    oos_predict["lgbm_oos_start"] = w.oos_start
    oos_predict["lgbm_oos_end"] = w.oos_end

    oos_predict["lgbm_anomaly_method"] = "IQR_1.5"

    lgbm_iqr_oos_predictions.append(oos_predict)

    lgbm_iqr_cv_results.append({

        "window": window_id,

        "train_start": w.train_start,
        "train_end": w.train_end,

        "oos_start": w.oos_start,
        "oos_end": w.oos_end,

        "n_train": len(X_train),
        "n_oos": len(X_oos),

        "best_cv_auc": lgbm_grid.best_score_,

        "best_n_estimators":
            lgbm_grid.best_params_["model__n_estimators"],

        "best_learning_rate":
            lgbm_grid.best_params_["model__learning_rate"],

        "best_num_leaves":
            lgbm_grid.best_params_["model__num_leaves"],

        "best_max_depth":
            lgbm_grid.best_params_["model__max_depth"],

        "best_subsample":
            lgbm_grid.best_params_["model__subsample"],

        "best_colsample_bytree":
            lgbm_grid.best_params_["model__colsample_bytree"],

        "anomaly_method":"IQR_1.5"

    })

    print(
        "Mean P(outperformance):",
        round(oos_predict["lgbm_probability"].mean(),4)
    )

======================================================================
STARTING ROLLING LIGHTGBM + IQR OOS PREDICTION
======================================================================

======================================================================
WINDOW 1
======================================================================
TRAIN : 2019-01 → 2023-12
OOS   : 2024-01 → 2024-03
Training observations: 646
OOS observations     : 96

Best parameters
{'model__colsample_bytree': 0.8, 'model__learning_rate': 0.1, 'model__max_depth': 8, 'model__n_estimators': 500, 'model__num_leaves': 31, 'model__subsample': 0.8}
Best CV ROC-AUC: 0.7414
Mean P(outperformance): 0.5451

======================================================================
WINDOW 2
======================================================================
TRAIN : 2019-04 → 2024-03
OOS   : 2024-04 → 2024-06
Training observations: 742
OOS observations     : 97

C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:95: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_probability"] = (
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_prediction"] = (
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_window"] = window_id
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:105: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_train_start"] = w.train_start
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_train_end"] = w.train_end
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_oos_start"] = w.oos_start
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:109: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_oos_end"] = w.oos_end
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:111: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_anomaly_method"] = "IQR_1.5"

Best parameters
{'model__colsample_bytree': 0.8, 'model__learning_rate': 0.1, 'model__max_depth': 5, 'model__n_estimators': 500, 'model__num_leaves': 31, 'model__subsample': 0.8}
Best CV ROC-AUC: 0.7046
Mean P(outperformance): 0.3766

======================================================================
WINDOW 3
======================================================================
TRAIN : 2019-07 → 2024-06
OOS   : 2024-07 → 2024-09
Training observations: 839
OOS observations     : 99

C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:95: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_probability"] = (
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_prediction"] = (
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_window"] = window_id
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:105: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_train_start"] = w.train_start
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_train_end"] = w.train_end
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_oos_start"] = w.oos_start
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:109: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_oos_end"] = w.oos_end
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:111: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_anomaly_method"] = "IQR_1.5"

Best parameters
{'model__colsample_bytree': 1.0, 'model__learning_rate': 0.1, 'model__max_depth': 8, 'model__n_estimators': 500, 'model__num_leaves': 31, 'model__subsample': 0.8}
Best CV ROC-AUC: 0.7041
Mean P(outperformance): 0.1572

======================================================================
WINDOW 4
======================================================================
TRAIN : 2019-10 → 2024-09
OOS   : 2024-10 → 2024-12
Training observations: 938
OOS observations     : 126

C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:95: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_probability"] = (
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_prediction"] = (
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_window"] = window_id
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:105: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_train_start"] = w.train_start
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_train_end"] = w.train_end
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_oos_start"] = w.oos_start
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:109: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_oos_end"] = w.oos_end
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:111: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_anomaly_method"] = "IQR_1.5"

Best parameters
{'model__colsample_bytree': 1.0, 'model__learning_rate': 0.1, 'model__max_depth': 8, 'model__n_estimators': 200, 'model__num_leaves': 31, 'model__subsample': 0.8}
Best CV ROC-AUC: 0.699
Mean P(outperformance): 0.431

======================================================================
WINDOW 5
======================================================================
TRAIN : 2020-01 → 2024-12
OOS   : 2025-01 → 2025-03
Training observations: 1064
OOS observations     : 220

C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:95: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_probability"] = (
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_prediction"] = (
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_window"] = window_id
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:105: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_train_start"] = w.train_start
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_train_end"] = w.train_end
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_oos_start"] = w.oos_start
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:109: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_oos_end"] = w.oos_end
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:111: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_anomaly_method"] = "IQR_1.5"

Best parameters
{'model__colsample_bytree': 0.8, 'model__learning_rate': 0.1, 'model__max_depth': 8, 'model__n_estimators': 200, 'model__num_leaves': 63, 'model__subsample': 0.8}
Best CV ROC-AUC: 0.6813
Mean P(outperformance): 0.1871

======================================================================
WINDOW 6
======================================================================
TRAIN : 2020-04 → 2025-03
OOS   : 2025-04 → 2025-06
Training observations: 1284
OOS observations     : 226

C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:95: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_probability"] = (
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_prediction"] = (
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_window"] = window_id
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:105: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_train_start"] = w.train_start
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_train_end"] = w.train_end
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_oos_start"] = w.oos_start
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:109: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_oos_end"] = w.oos_end
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:111: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_anomaly_method"] = "IQR_1.5"

Best parameters
{'model__colsample_bytree': 1.0, 'model__learning_rate': 0.05, 'model__max_depth': 8, 'model__n_estimators': 200, 'model__num_leaves': 63, 'model__subsample': 0.8}
Best CV ROC-AUC: 0.6597
Mean P(outperformance): 0.5427

======================================================================
WINDOW 7
======================================================================
TRAIN : 2020-07 → 2025-06
OOS   : 2025-07 → 2025-09
Training observations: 1510
OOS observations     : 235

C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:95: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_probability"] = (
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_prediction"] = (
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_window"] = window_id
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:105: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_train_start"] = w.train_start
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_train_end"] = w.train_end
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_oos_start"] = w.oos_start
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:109: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_oos_end"] = w.oos_end
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:111: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_anomaly_method"] = "IQR_1.5"

Best parameters
{'model__colsample_bytree': 1.0, 'model__learning_rate': 0.05, 'model__max_depth': 8, 'model__n_estimators': 200, 'model__num_leaves': 63, 'model__subsample': 0.8}
Best CV ROC-AUC: 0.6777
Mean P(outperformance): 0.8532

======================================================================
WINDOW 8
======================================================================
TRAIN : 2020-10 → 2025-09
OOS   : 2025-10 → 2025-12
Training observations: 1745
OOS observations     : 247

C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:95: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_probability"] = (
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_prediction"] = (
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_window"] = window_id
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:105: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_train_start"] = w.train_start
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_train_end"] = w.train_end
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_oos_start"] = w.oos_start
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:109: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_oos_end"] = w.oos_end
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:111: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_anomaly_method"] = "IQR_1.5"

Best parameters
{'model__colsample_bytree': 0.8, 'model__learning_rate': 0.1, 'model__max_depth': 8, 'model__n_estimators': 200, 'model__num_leaves': 63, 'model__subsample': 0.8}
Best CV ROC-AUC: 0.6811
Mean P(outperformance): 0.5486

C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:95: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_probability"] = (
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_prediction"] = (
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:103: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_window"] = window_id
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:105: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_train_start"] = w.train_start
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_train_end"] = w.train_end
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:108: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_oos_start"] = w.oos_start
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:109: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_oos_end"] = w.oos_end
C:\Users\Admin\AppData\Local\Temp\ipykernel_11376\4259751546.py:111: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oos_predict["lgbm_anomaly_method"] = "IQR_1.5"

In [17]:
lgbm_iqr_oos_df = pd.concat(
    lgbm_iqr_oos_predictions,
    ignore_index=True
)

lgbm_iqr_cv_results_df = pd.DataFrame(
    lgbm_iqr_cv_results
)

print("="*70)
print("LIGHTGBM + IQR COMPLETE")
print("="*70)

print("Predictions :", len(lgbm_iqr_oos_df))
print("Funds       :", lgbm_iqr_oos_df.scheme_name.nunique())
print("Months      :", lgbm_iqr_oos_df.month_date.nunique())

======================================================================
LIGHTGBM + IQR COMPLETE
======================================================================
Predictions : 1346
Funds       : 85
Months      : 24

In [18]:
target_errors = (
    lgbm_iqr_oos_df.target_month !=
    lgbm_iqr_oos_df.month_date + pd.DateOffset(months=1)
).sum()

duplicates = (
    lgbm_iqr_oos_df
      .groupby(["scheme_name","month_date"])
      .size()
      .gt(1)
      .sum()
)

probability_errors = (
    (lgbm_iqr_oos_df.lgbm_probability < 0) |
    (lgbm_iqr_oos_df.lgbm_probability > 1)
).sum()

print("="*70)
print("LIGHTGBM + IQR INTEGRITY CHECK")
print("="*70)

print("Target alignment errors :", target_errors)
print("Duplicate fund-months   :", duplicates)
print("Probability errors      :", probability_errors)
print("Windows                 :", lgbm_iqr_oos_df.lgbm_window.nunique())
print("Months                  :", lgbm_iqr_oos_df.month_date.nunique())

======================================================================
LIGHTGBM + IQR INTEGRITY CHECK
======================================================================
Target alignment errors : 0
Duplicate fund-months   : 0
Probability errors      : 0
Windows                 : 8
Months                  : 24

In [20]:


prediction_table = (
    f"exclude_covid_oos_predictions_lgbm_iqr_{RUN_TIMESTAMP}"
)

cv_table = (
    f"exclude_covid_lgbm_iqr_cv_results_{RUN_TIMESTAMP}"
)

lgbm_db = lgbm_iqr_oos_df[[
    "scheme_name",
    "month_date",
    "target_month",
    "lgbm_probability",
    "lgbm_prediction",
    "lgbm_window",
    "lgbm_train_start",
    "lgbm_train_end",
    "lgbm_oos_start",
    "lgbm_oos_end",
    "lgbm_anomaly_method"
]]

lgbm_db.to_sql(
    prediction_table,
    engine,
    schema="mf200",
    if_exists="fail",
    index=False
)

lgbm_iqr_cv_results_df.to_sql(
    cv_table,
    engine,
    schema="mf200",
    if_exists="fail",
    index=False
)

print("="*70)
print("LIGHTGBM + IQR RESULTS SAVED")
print("="*70)
print("Prediction table :", f"mf200.{prediction_table}")
print("Rows             :", len(lgbm_db))
print("Funds            :", lgbm_db.scheme_name.nunique())
print("Months           :", lgbm_db.month_date.nunique())

print()
print("CV table :", f"mf200.{cv_table}")
print("CV rows  :", len(lgbm_iqr_cv_results_df))

======================================================================
LIGHTGBM + IQR RESULTS SAVED
======================================================================
Prediction table : mf200.exclude_covid_oos_predictions_lgbm_iqr_20260905_003517
Rows             : 1346
Funds            : 85
Months           : 24

CV table : mf200.exclude_covid_lgbm_iqr_cv_results_20260905_003517
CV rows  : 8