In [ ]:
# SELECTED_FEATURES_IC = [
#     "t_hml_750",
#     "t_hml_250",
#     "t_hml_180",
#     "ir_p1y",
#     "sr_p1y",
#     "ir_p3y",
#     "t_hml_120",
#     "t_const_250",
#     "ir_p6m",
#     "sr_p3y",
#     "t_hml_90",
#     "t_const_180",
#     "sr_p6m",
#     "const_250",
#     "const_180",
#     "const_90",
#     "t_const_90",
#     "t_umd_750",
#     "const_120",
#     "t_const_120",
#     "t_smb_750",
#     "r2_750",
# ]

In [1]:
# ============================================================
# RANDOM FOREST MODEL
# CONFIGURATION
# ============================================================

import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import roc_auc_score


# ------------------------------------------------------------
# MODEL SETTINGS
# ------------------------------------------------------------

RANDOM_STATE = 42

TARGET = "outperforms_benchmark"


# ------------------------------------------------------------
# IC-SELECTED FEATURES
# ------------------------------------------------------------

selected_features = [
    "t_hml_250",
    "t_hml_750",
    "t_hml_180",
    "sr_p1y",
    "ir_p1y",
    "ir_p6m",
    "monthly_return_percent",
    "t_const_180",
    "sr_p6m",
    "t_const_250",
    "ir_p3y",
    "const_90",
    "const_180",
    "t_const_90",
    "t_const_120",
    "const_250",
    "t_hml_120",
    "const_120",
    "t_mkt_750",
    "t_umd_750",
    "t_hml_90",
    "sr_p3y",
    "r2_750",
    "net_flow_percent",
    "t_smb_250"
]


# ------------------------------------------------------------
# OPTIONAL FEATURE DROPPING
# ------------------------------------------------------------
# Leave empty to use all 25 features.
#
# Example:
# DROP_FEATURES = ["net_flow_percent"]
#
# Multiple:
# DROP_FEATURES = [
#     "net_flow_percent",
#     "r2_750"
# ]

DROP_FEATURES = []


# ------------------------------------------------------------
# FINAL FEATURES USED BY RF
# ------------------------------------------------------------

rf_features = [
    f for f in selected_features
    if f not in DROP_FEATURES
]


# ------------------------------------------------------------
# VALIDATION
# ------------------------------------------------------------

unknown_drops = [
    f for f in DROP_FEATURES
    if f not in selected_features
]

if unknown_drops:
    raise ValueError(
        f"DROP_FEATURES contains features that are not "
        f"in selected_features: {unknown_drops}"
    )


print("=" * 70)
print("RANDOM FOREST CONFIGURATION")
print("=" * 70)

print(f"Original IC-selected features : {len(selected_features)}")
print(f"Dropped features              : {len(DROP_FEATURES)}")
print(f"Features used by RF           : {len(rf_features)}")

if DROP_FEATURES:
    print("\nDropped:")
    for f in DROP_FEATURES:
        print(f"  - {f}")

print("\nFeatures used:")
for i, f in enumerate(rf_features, 1):
    print(f"{i:2d}. {f}")

======================================================================
RANDOM FOREST CONFIGURATION
======================================================================
Original IC-selected features : 25
Dropped features              : 0
Features used by RF           : 25

Features used:
 1. t_hml_250
 2. t_hml_750
 3. t_hml_180
 4. sr_p1y
 5. ir_p1y
 6. ir_p6m
 7. monthly_return_percent
 8. t_const_180
 9. sr_p6m
10. t_const_250
11. ir_p3y
12. const_90
13. const_180
14. t_const_90
15. t_const_120
16. const_250
17. t_hml_120
18. const_120
19. t_mkt_750
20. t_umd_750
21. t_hml_90
22. sr_p3y
23. r2_750
24. net_flow_percent
25. t_smb_250

In [2]:
# ============================================================
# PREPARE MODEL DATA
# ============================================================
# Load dataset
df = pd.read_csv('D:\\PycharmProjects\\mf-ml\\feature_selection_output\\ml_feature_dataset.csv')

model_df = df.copy()

print("\nmodel_df shape:", model_df.shape)

print(
    "Date range:",
    model_df["month_date"].min(),
    "→",
    model_df["month_date"].max()
)

print(
    "\nMissing values in RF features:"
)

print(
    model_df[rf_features]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

# ------------------------------------------------------------
# Convert date columns
# ------------------------------------------------------------

model_df["month_date"] = pd.to_datetime(
    model_df["month_date"],
    errors="coerce"
)

model_df["target_month"] = pd.to_datetime(
    model_df["target_month"],
    errors="coerce"
)

# ------------------------------------------------------------
# Validate dates
# ------------------------------------------------------------

assert model_df["month_date"].notna().all(), (
    "Invalid values found in month_date."
)

assert model_df["target_month"].notna().all(), (
    "Invalid values found in target_month."
)

print("model_df shape:", model_df.shape)

print(
    "Date range:",
    model_df["month_date"].min(),
    "→",
    model_df["month_date"].max()
)

print(
    "month_date dtype:",
    model_df["month_date"].dtype
)

print(
    "\nMissing values in RF features:"
)

display(
    model_df[rf_features]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

model_df shape: (7034, 29)
Date range: 2019-01-01 → 2026-06-01

Missing values in RF features:
t_hml_750                 5042
t_mkt_750                 5042
t_umd_750                 5042
r2_750                    5042
sr_p3y                    5042
ir_p3y                    5042
t_hml_250                 2618
ir_p1y                    2618
sr_p1y                    2618
const_250                 2618
t_const_250               2618
t_smb_250                 2618
const_180                 2154
t_hml_180                 2154
t_const_180               2154
ir_p6m                    1791
sr_p6m                    1791
t_const_120               1720
const_120                 1720
t_hml_120                 1720
t_const_90                1543
t_hml_90                  1543
const_90                  1543
monthly_return_percent     185
net_flow_percent           185
dtype: int64
model_df shape: (7034, 29)
Date range: 2019-01-01 00:00:00 → 2026-06-01 00:00:00
month_date dtype: datetime64[ns]

Missing values in RF features:

t_hml_750                 5042
t_mkt_750                 5042
t_umd_750                 5042
r2_750                    5042
sr_p3y                    5042
ir_p3y                    5042
t_hml_250                 2618
ir_p1y                    2618
sr_p1y                    2618
const_250                 2618
t_const_250               2618
t_smb_250                 2618
const_180                 2154
t_hml_180                 2154
t_const_180               2154
ir_p6m                    1791
sr_p6m                    1791
t_const_120               1720
const_120                 1720
t_hml_120                 1720
t_const_90                1543
t_hml_90                  1543
const_90                  1543
monthly_return_percent     185
net_flow_percent           185
dtype: int64

In [3]:
# ============================================================
# ROLLING WINDOW CONFIGURATION
# ============================================================

MODEL_START_MONTH = pd.Timestamp("2019-01-01")
MODEL_END_MONTH   = pd.Timestamp("2025-12-01")

INITIAL_TRAIN_MONTHS = 60
OOS_MONTHS = 3
ROLL_MONTHS = 3

# ============================================================
# COVID PERIOD EXCLUSION
# ============================================================

EXCLUDE_COVID = True

COVID_START = pd.Timestamp("2020-01-01")
COVID_END   = pd.Timestamp("2021-12-01")

rolling_windows = []

train_start = MODEL_START_MONTH

window_id = 1

while True:

    train_end = (
        train_start
        + pd.DateOffset(months=INITIAL_TRAIN_MONTHS - 1)
    )

    oos_start = train_end + pd.DateOffset(months=1)

    oos_end = (
        oos_start
        + pd.DateOffset(months=OOS_MONTHS - 1)
    )

    if oos_end > MODEL_END_MONTH:
        break

    rolling_windows.append({
        "window": window_id,
        "train_start": train_start,
        "train_end": train_end,
        "oos_start": oos_start,
        "oos_end": oos_end
    })

    train_start = (
        train_start
        + pd.DateOffset(months=ROLL_MONTHS)
    )

    window_id += 1


rolling_windows_df = pd.DataFrame(
    rolling_windows
)

print(
    "Number of rolling windows:",
    len(rolling_windows_df)
)

display(rolling_windows_df)

Number of rolling windows: 8

   window train_start  train_end  oos_start    oos_end
0       1  2019-01-01 2023-12-01 2024-01-01 2024-03-01
1       2  2019-04-01 2024-03-01 2024-04-01 2024-06-01
2       3  2019-07-01 2024-06-01 2024-07-01 2024-09-01
3       4  2019-10-01 2024-09-01 2024-10-01 2024-12-01
4       5  2020-01-01 2024-12-01 2025-01-01 2025-03-01
5       6  2020-04-01 2025-03-01 2025-04-01 2025-06-01
6       7  2020-07-01 2025-06-01 2025-07-01 2025-09-01
7       8  2020-10-01 2025-09-01 2025-10-01 2025-12-01

In [4]:
# ============================================================
# REMOVE EXCLUDED PERIOD FROM TRAINING DATA
# ============================================================

def exclude_covid_period(df):

    if not EXCLUDE_COVID:
        return df.copy()

    mask = ~(
        (df["month_date"] >= COVID_START) &
        (df["month_date"] <= COVID_END)
    )

    return df.loc[mask].copy()

In [5]:
# ============================================================
# RANDOM FOREST HYPERPARAMETER GRID
# ============================================================

rf_param_grid = {
    "model__n_estimators": [
        200,
        500
    ],

    "model__max_depth": [
        None,
        5,
        10
    ],

    "model__min_samples_leaf": [
        5,
        10,
        20
    ]
}

print("RF parameter combinations:")

n_combinations = 1

for values in rf_param_grid.values():
    n_combinations *= len(values)

print(n_combinations)

RF parameter combinations:
18

In [6]:
# ============================================================
# CROSS-SECTIONAL CV SPLITS
# ============================================================

def make_cross_sectional_splits(
    df,
    n_splits=5
):
    """
    Create cross-sectional validation splits.

    Each fold uses entire months as validation periods,
    preventing observations from the same month from being
    split between training and validation.
    """

    months = (
        pd.Series(
            df["month_date"]
            .dropna()
            .unique()
        )
        .sort_values()
        .reset_index(drop=True)
    )

    month_folds = np.array_split(
        months,
        n_splits
    )

    splits = []

    for fold_months in month_folds:

        if len(fold_months) == 0:
            continue

        validation_mask = (
            df["month_date"]
            .isin(fold_months)
        )

        train_idx = np.where(
            ~validation_mask
        )[0]

        validation_idx = np.where(
            validation_mask
        )[0]

        splits.append(
            (
                train_idx,
                validation_idx
            )
        )

    return splits

In [7]:
from sklearn.model_selection import KFold
# ============================================================
# RANDOM FOREST — ROLLING CV + OOS
# ============================================================

rf_oos_predictions = []

rf_cv_results = []


for _, w in rolling_windows_df.iterrows():

    window_id = int(w["window"])

    print("\n")
    print("=" * 70)
    print(f"WINDOW {window_id}")
    print("=" * 70)

    print(
        f"TRAIN: {w['train_start']:%Y-%m}"
        f" → "
        f"{w['train_end']:%Y-%m}"
    )

    print(
        f"OOS:   {w['oos_start']:%Y-%m}"
        f" → "
        f"{w['oos_end']:%Y-%m}"
    )


    # --------------------------------------------------------
    # TRAINING DATA
    # --------------------------------------------------------

    train = model_df[
        (model_df["month_date"] >= w["train_start"]) &
        (model_df["month_date"] <= w["train_end"])
    ].copy()

    train = exclude_covid_period(train)

    train = train.dropna(
        subset=rf_features + [TARGET]
    ).copy()

    X_train = train[rf_features]
    y_train = train[TARGET].astype(int)


    # --------------------------------------------------------
    # OOS DATA
    # --------------------------------------------------------

    oos = model_df[
        (model_df["month_date"] >= w["oos_start"]) &
        (model_df["month_date"] <= w["oos_end"])
    ].copy()

    oos_predict = oos.dropna(
        subset=rf_features
    ).copy()

    X_oos = oos_predict[rf_features]


    print(
        f"Training observations: {len(train):,}"
    )

    print(
        f"OOS observations:      {len(oos_predict):,}"
    )


    # # --------------------------------------------------------
    # # CROSS-SECTIONAL CV
    # # --------------------------------------------------------
    #
    # cv_splits = make_cross_sectional_splits(
    #     train,
    #     n_splits=5
    # )

    # ============================================================
    # K-FOLD CROSS-VALIDATION
    # ============================================================

    cv = KFold(
        n_splits=5,
        shuffle=True,
        random_state=RANDOM_STATE
    )
    # --------------------------------------------------------
    # RF PIPELINE
    # --------------------------------------------------------

    rf_pipeline = Pipeline([
        (
            "scaler",
            StandardScaler()
        ),

        (
            "model",
            RandomForestClassifier(
                random_state=RANDOM_STATE,
                n_jobs=-1,
                class_weight="balanced"
            )
        )
    ])


    # --------------------------------------------------------
    # GRID SEARCH
    # --------------------------------------------------------

    grid_search = GridSearchCV(
        estimator=rf_pipeline,
        param_grid=rf_param_grid,
        scoring="roc_auc",
        cv=cv,
        #cv=cv_splits,
        n_jobs=-1,
        refit=True
    )


    grid_search.fit(
        X_train,
        y_train
    )


    # --------------------------------------------------------
    # BEST PARAMETERS
    # --------------------------------------------------------

    best_params = grid_search.best_params_

    best_cv_auc = grid_search.best_score_


    print("\nBest parameters:")
    print(best_params)

    print(
        f"Best CV ROC-AUC: {best_cv_auc:.4f}"
    )


    # --------------------------------------------------------
    # OOS PREDICTION
    # --------------------------------------------------------

    oos_predict["rf_probability"] = (
        grid_search.predict_proba(X_oos)[:, 1]
    )

    oos_predict["rf_prediction"] = (
        grid_search.predict(X_oos)
    )


    # --------------------------------------------------------
    # WINDOW METADATA
    # --------------------------------------------------------

    oos_predict["rf_window"] = window_id

    oos_predict["rf_train_start"] = (
        w["train_start"]
    )

    oos_predict["rf_train_end"] = (
        w["train_end"]
    )

    oos_predict["rf_oos_start"] = (
        w["oos_start"]
    )

    oos_predict["rf_oos_end"] = (
        w["oos_end"]
    )


    rf_oos_predictions.append(
        oos_predict
    )


    # --------------------------------------------------------
    # SAVE CV RESULT
    # --------------------------------------------------------

    rf_cv_results.append({
        "window": window_id,
        "train_start": w["train_start"],
        "train_end": w["train_end"],
        "oos_start": w["oos_start"],
        "oos_end": w["oos_end"],
        "n_train": len(train),
        "n_oos": len(oos_predict),
        "best_cv_auc": best_cv_auc,
        "best_n_estimators":
            best_params["model__n_estimators"],
        "best_max_depth":
            best_params["model__max_depth"],
        "best_min_samples_leaf":
            best_params["model__min_samples_leaf"]
    })


    print(
        f"Mean P(outperformance): "
        f"{oos_predict['rf_probability'].mean():.4f}"
    )


# ============================================================
# COMBINE ALL OOS PREDICTIONS
# ============================================================

rf_oos_df = pd.concat(
    rf_oos_predictions,
    ignore_index=True
)

rf_cv_results_df = pd.DataFrame(
    rf_cv_results
)


print("\n")
print("=" * 70)
print("RF OOS PREDICTION COMPLETE")
print("=" * 70)

print(
    "Total OOS predictions:",
    len(rf_oos_df)
)

print(
    "Unique funds:",
    rf_oos_df["scheme_name"].nunique()
)

print(
    "OOS months:",
    rf_oos_df["month_date"].nunique()
)

display(
    rf_cv_results_df
)

======================================================================
WINDOW 1
======================================================================
TRAIN: 2019-01 → 2023-12
OOS:   2024-01 → 2024-03
Training observations: 646
OOS observations:      96

d:\PycharmProjects\mf-ml\.venv\Lib\site-packages\numpy\_core\fromnumeric.py:54: FutureWarning: 'Series.swapaxes' is deprecated and will be removed in a future version. Please use 'Series.transpose' instead.
  return bound(*args, **kwds)

Best parameters:
{'model__max_depth': None, 'model__min_samples_leaf': 10, 'model__n_estimators': 500}
Best CV ROC-AUC: 0.5948
Mean P(outperformance): 0.4766


======================================================================
WINDOW 2
======================================================================
TRAIN: 2019-04 → 2024-03
OOS:   2024-04 → 2024-06
Training observations: 742
OOS observations:      97

d:\PycharmProjects\mf-ml\.venv\Lib\site-packages\numpy\_core\fromnumeric.py:54: FutureWarning: 'Series.swapaxes' is deprecated and will be removed in a future version. Please use 'Series.transpose' instead.
  return bound(*args, **kwds)

Best parameters:
{'model__max_depth': 5, 'model__min_samples_leaf': 5, 'model__n_estimators': 200}
Best CV ROC-AUC: 0.5799
Mean P(outperformance): 0.4517


======================================================================
WINDOW 3
======================================================================
TRAIN: 2019-07 → 2024-06
OOS:   2024-07 → 2024-09
Training observations: 839
OOS observations:      99

d:\PycharmProjects\mf-ml\.venv\Lib\site-packages\numpy\_core\fromnumeric.py:54: FutureWarning: 'Series.swapaxes' is deprecated and will be removed in a future version. Please use 'Series.transpose' instead.
  return bound(*args, **kwds)

Best parameters:
{'model__max_depth': 5, 'model__min_samples_leaf': 5, 'model__n_estimators': 500}
Best CV ROC-AUC: 0.5513
Mean P(outperformance): 0.4196


======================================================================
WINDOW 4
======================================================================
TRAIN: 2019-10 → 2024-09
OOS:   2024-10 → 2024-12
Training observations: 938
OOS observations:      126

d:\PycharmProjects\mf-ml\.venv\Lib\site-packages\numpy\_core\fromnumeric.py:54: FutureWarning: 'Series.swapaxes' is deprecated and will be removed in a future version. Please use 'Series.transpose' instead.
  return bound(*args, **kwds)

Best parameters:
{'model__max_depth': 5, 'model__min_samples_leaf': 20, 'model__n_estimators': 500}
Best CV ROC-AUC: 0.5114
Mean P(outperformance): 0.5192


======================================================================
WINDOW 5
======================================================================
TRAIN: 2020-01 → 2024-12
OOS:   2025-01 → 2025-03
Training observations: 1,064
OOS observations:      220

d:\PycharmProjects\mf-ml\.venv\Lib\site-packages\numpy\_core\fromnumeric.py:54: FutureWarning: 'Series.swapaxes' is deprecated and will be removed in a future version. Please use 'Series.transpose' instead.
  return bound(*args, **kwds)

Best parameters:
{'model__max_depth': 5, 'model__min_samples_leaf': 10, 'model__n_estimators': 500}
Best CV ROC-AUC: 0.5757
Mean P(outperformance): 0.4123


======================================================================
WINDOW 6
======================================================================
TRAIN: 2020-04 → 2025-03
OOS:   2025-04 → 2025-06
Training observations: 1,284
OOS observations:      226

d:\PycharmProjects\mf-ml\.venv\Lib\site-packages\numpy\_core\fromnumeric.py:54: FutureWarning: 'Series.swapaxes' is deprecated and will be removed in a future version. Please use 'Series.transpose' instead.
  return bound(*args, **kwds)

Best parameters:
{'model__max_depth': 5, 'model__min_samples_leaf': 5, 'model__n_estimators': 500}
Best CV ROC-AUC: 0.5394
Mean P(outperformance): 0.4956


======================================================================
WINDOW 7
======================================================================
TRAIN: 2020-07 → 2025-06
OOS:   2025-07 → 2025-09
Training observations: 1,510
OOS observations:      235

d:\PycharmProjects\mf-ml\.venv\Lib\site-packages\numpy\_core\fromnumeric.py:54: FutureWarning: 'Series.swapaxes' is deprecated and will be removed in a future version. Please use 'Series.transpose' instead.
  return bound(*args, **kwds)

Best parameters:
{'model__max_depth': 5, 'model__min_samples_leaf': 5, 'model__n_estimators': 200}
Best CV ROC-AUC: 0.5626
Mean P(outperformance): 0.5673


======================================================================
WINDOW 8
======================================================================
TRAIN: 2020-10 → 2025-09
OOS:   2025-10 → 2025-12
Training observations: 1,745
OOS observations:      247

d:\PycharmProjects\mf-ml\.venv\Lib\site-packages\numpy\_core\fromnumeric.py:54: FutureWarning: 'Series.swapaxes' is deprecated and will be removed in a future version. Please use 'Series.transpose' instead.
  return bound(*args, **kwds)

Best parameters:
{'model__max_depth': 5, 'model__min_samples_leaf': 5, 'model__n_estimators': 500}
Best CV ROC-AUC: 0.5195
Mean P(outperformance): 0.4599


======================================================================
RF OOS PREDICTION COMPLETE
======================================================================
Total OOS predictions: 1346
Unique funds: 85
OOS months: 24

,window,train_start,train_end,oos_start,oos_end,n_train,n_oos,best_cv_auc,best_n_estimators,best_max_depth,best_min_samples_leaf
0,1,2019-01-01,2023-12-01,2024-01-01,2024-03-01,646,96,0.594782,500,NaN,10
1,2,2019-04-01,2024-03-01,2024-04-01,2024-06-01,742,97,0.579944,200,5.0,5
2,3,2019-07-01,2024-06-01,2024-07-01,2024-09-01,839,99,0.551304,500,5.0,5
3,4,2019-10-01,2024-09-01,2024-10-01,2024-12-01,938,126,0.511378,500,5.0,20
4,5,2020-01-01,2024-12-01,2025-01-01,2025-03-01,1064,220,0.575715,500,5.0,10
5,6,2020-04-01,2025-03-01,2025-04-01,2025-06-01,1284,226,0.539408,500,5.0,5
6,7,2020-07-01,2025-06-01,2025-07-01,2025-09-01,1510,235,0.562614,200,5.0,5
7,8,2020-10-01,2025-09-01,2025-10-01,2025-12-01,1745,247,0.519543,500,5.0,5

In [8]:
# ============================================================
# CHECK RF OOS PREDICTIONS
# ============================================================

print("RF OOS shape:", rf_oos_df.shape)

display(
    rf_oos_df[
        [
            "scheme_name",
            "month_date",
            "target_month",
            "rf_probability",
            "rf_prediction",
            "rf_window"
        ]
    ].head()
)

RF OOS shape: (1346, 36)

,scheme_name,month_date,target_month,rf_probability,rf_prediction,rf_window
0,Axis Flexi Cap Fund,2024-01-01,2024-02-01,0.307957,0,1
1,DSP ELSS Tax Saver Fund,2024-01-01,2024-02-01,0.413768,0,1
2,DSP Flexi Cap Fund,2024-01-01,2024-02-01,0.432798,0,1
3,Edelweiss ELSS Tax saver Fund,2024-01-01,2024-02-01,0.337334,0,1
4,Edelweiss Flexi Cap Fund,2024-01-01,2024-02-01,0.338790,0,1

In [9]:
# ============================================================
# PREPARE RF PREDICTIONS FOR DATABASE
# ============================================================

rf_db = rf_oos_df[
    [
        "scheme_name",
        "month_date",
        "target_month",
        "rf_probability",
        "rf_prediction",
        "rf_window",
        "rf_train_start",
        "rf_train_end",
        "rf_oos_start",
        "rf_oos_end"
    ]
].copy()

print("Rows to save:", len(rf_db))

Rows to save: 1346

In [10]:
# ============================================================
# 1. DATABASE CONNECTION
# ============================================================

from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:Password%40123@localhost:5432/mfdb"
)

print(type(engine))

print("Database engine created.")

<class 'sqlalchemy.engine.base.Engine'>
Database engine created.

In [14]:
# ============================================================
# SAVE RF OOS PREDICTIONS TO A NEW TABLE
# ============================================================

from datetime import datetime

# ------------------------------------------------------------
# Create timestamped table name
# ------------------------------------------------------------

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

table_name = f"exclude_covid_oos_predictions_rf_{timestamp}"

print("Saving RF predictions to:")
print(f"mf200.{table_name}")


# ------------------------------------------------------------
# Select columns to persist
# ------------------------------------------------------------

rf_db = rf_oos_df[
    [
        "scheme_name",
        "month_date",
        "target_month",

        # RF prediction
        "rf_probability",
        "rf_prediction",

        # Rolling-window information
        "rf_window",
        "rf_train_start",
        "rf_train_end",
        "rf_oos_start",
        "rf_oos_end"
    ]
].copy()


# ------------------------------------------------------------
# Save as a NEW table
# ------------------------------------------------------------

rf_db.to_sql(
    name=table_name,
    con=engine,
    schema="mf200",
    if_exists="fail",
    index=False
)


# ------------------------------------------------------------
# Confirmation
# ------------------------------------------------------------

print()
print("=" * 70)
print("RF PREDICTIONS SAVED")
print("=" * 70)

print(
    f"Table: mf200.{table_name}"
)

print(
    f"Rows : {len(rf_db):,}"
)

print(
    f"Funds: {rf_db['scheme_name'].nunique():,}"
)

print(
    f"Months: {rf_db['month_date'].nunique():,}"
)

Saving RF predictions to:
mf200.exclude_covid_oos_predictions_rf_20260831_224127

======================================================================
RF PREDICTIONS SAVED
======================================================================
Table: mf200.exclude_covid_oos_predictions_rf_20260831_224127
Rows : 1,346
Funds: 85
Months: 24